.github/workflows/actions.yml, api/.editorconfig, client/.eslintignore, client/.eslintrc.js, client/.prettierignore, client/.prettierrc, client/package-lock.json, client/package.json, client/src/pages/api/hello.ts
https://framgiaph.backlog.com/view/HRIS-26
Reviewer should have access to `Actions` tab of the repository to check results
- to check JS format, run `npm check-format` in `client` directory
- to check JS lint, run `npm check-lint` in `client` directory
- to check .NET/C# format, run `dotnet format --verify-no-changes` in `api` directory
- ESLint Rules
&nbsp; - no console log
&nbsp; - Required EOF new line
&nbsp; - No Duplicate imports
&nbsp; - 'React' must be imported when using JSX
&nbsp; - 'React' must be imported when using JSX
&nbsp; - `@typescript-eslint/consistent-type-definitions` that enforces the use of interface for type definitions is disabled
- Prettier Rules
&nbsp; - No semi colon at EOL
&nbsp; - Tab size is 2 spaces
&nbsp; - use single quotes
&nbsp; - No trailing commas
- …
=> [HRIS-26] - [Dev] Setup GitHub Actions

api/Context/HrisContext.cs, api/Entities/Personal_Access_Token.cs, api/Migrations/20230112090508_Personal_Access_Tokens.Designer.cs, api/Migrations/20230112090508_Personal_Access_Tokens.cs, api/Program.cs, api/Requests/SigninRequest.cs, api/Schema/Mutations/SigninMutation.cs, api/Services/SigninService.cs, api/api.csproj
https://framgiaph.backlog.com/view/HRIS-11
- For now, mutation can only add tokens
- Also, successful and unsuccessful query of email will for now returns a message.
- Backend integration only
- run ```docker compose up --build```
- Open another termina and run ```cd api```
- Run ```dotnet ef database update```
- Access ```http://localhost:5257/graphql/``` in your browser
- Run the mutation:
- ```mutation {
createSignIn (signIn:
{
email: "johndoe@sun-asterisk.com",
token: "adasdasdasdasdasdasd",
expiration: "PT9H30M"
})}
If the email is valid, it should return ```{
"data": {
"createSignIn": "Successful Log In!"
}
}```
else it will return ```{
"data": {
"createSignIn": "You don't have permission to access this page."
}
}```
Invalid User
Valid User
Personal_Access_Token
=> HRIS-11 [BE] Create login functionality

api/Requests/CreateInterruptionRequest.cs, api/Schema/Queries/InterruptionQuery.cs, api/Services/InterruptionService.cs, client/src/components/organisms/Header/index.tsx, client/src/components/organisms/WorkInterruptionDrawer/index.tsx, client/src/graphql/mutations/workInterruptionMutation.ts, client/src/graphql/queries/workInterruptionQuery.ts, client/src/hooks/useInterruptionType.ts, client/src/utils/constants/work-status.ts, client/src/utils/types/formValues.ts, client/src/utils/types/workInterruptionTypes.ts, client/src/utils/validation/index.ts
https://framgiaph.backlog.com/view/HRIS-60
- Please don't forget to create a time entry first using your tableplus (if not yet created) for the authenticated user and do a time in before submitting an interruption
- Create a time entry first if not yet created
- Submit a time in
- Click the break button
- It should be able to submit a work interruption and perform the conditions as stated in the definition of done
https://user-images.githubusercontent.com/110364637/213419333-4eb91eb3-c624-4079-a868-bdc542b6df11.mp4
=> HRIS-60 [FE] Integrate file work interruption request functionality

api/Services/TimeSheetService.cs
https://framgiaph.backlog.com/view/HRIS-43
- BE Integration only
- In the root terminal, run ``` docker compose up --build ```
- Existing Time Entry with a file attached
- Upon query, it will return remarks and attached File details
=> HRIS-43 [BE] Implement GET remarks and uploaded files on the time entry

api/DTOs/TimeEntryDTO.cs, client/package-lock.json, client/src/components/molecules/MyDailyTimeRecordTable/index.tsx, client/src/pages/my-daily-time-record.tsx
https://framgiaph.backlog.com/view/HRIS-46
- Also fixed the query error occurring in MyDTR page
- `docker compose up --build` or `dotnet watch` in `api` directory
- go to `http://localhost:5257/graphql/` and use this query
```
query Summary($startDate: String, $endDate:String){
timesheetSummary(
startDate: $startDate
endDate: $endDate
) {
user{
name
}
leave
absences
late
undertime
overtime
}
}
```
- with these variables
```
{
"startDate": "2023-01-01",
"endDate": "2023-01-30"
}
```
- Noon break should now be deducted in computation of `Undertime` value 
- Sample query
=> HRIS-46-01 [FE] Revised computation of undertime

api/DTOs/TimeEntryDTO.cs, api/DTOs/UserDTO.cs, api/Entities/TimeEntry.cs, api/Migrations/20230127083633_UpdateDefaultTimestamps.Designer.cs, api/Migrations/20230127083633_UpdateDefaultTimestamps.cs, api/Migrations/20230127083829_UpdateWorkedHoursType.Designer.cs, api/Migrations/20230127083829_UpdateWorkedHoursType.cs, api/Requests/TimeOutRequest.cs, api/Seeders/DatabaseSeeder.cs, api/Services/TimeOutService.cs, client/src/components/organisms/Header/index.tsx, client/src/components/organisms/TimeOutDrawer/index.tsx, client/src/components/templates/Layout/index.tsx, client/src/hooks/useTimeOutMutation.ts
https://framgiaph.backlog.com/view/HRIS-63
Optional
- Please migrate first to the database using `dotnet ef database update`
- `cd api`
- `dotnet ef database update`
- User should be able to logout on the day he or she was not able to logout and the timer should continue running
https://user-images.githubusercontent.com/110364637/215075708-dd8126fd-2c11-4a1b-b096-904370398eab.mp4
=> HRIS-63 [BugTask] Clock out error

client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx, client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx, client/src/pages/my-leaves.tsx
https://framgiaph.backlog.com/view/HRIS-74
https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=2400%3A21133&t=cEJpxD0AABWxDLCr-4
cd client && npm install && npm run dev
- It should now a markup for My Leaves Page with reusable component from previous PR
- With pre-defined dummy data and random leaves color scheme
[test2.webm](https://user-images.githubusercontent.com/108642414/215660549-9b782cbb-410a-4899-9129-f1b018af63fc.webm)
=> HRIS-74 [Markup] Create My Leaves Page

client/src/components/organisms/Header/index.tsx
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-99)
run docker
visit localhost:3000
Add legends to my-daily-time-record page
=> HRIS-99 [Markup] Add legends to My DTR page

api/DTOs/TimeEntryDTO.cs, client/package-lock.json, client/src/components/molecules/LegendTooltip/index.tsx, client/src/components/molecules/TimeSheetFilterDropdown/index.tsx, client/src/utils/constants/work-status.ts
https://framgiaph.backlog.com/view/HRIS-99#comment-134623719
run docker
visit localhost:3000
Updated the wording for the legends
=> HRIS-99-01 [Markup] Updated legends for mydtrpage and dtr management

client/src/components/molecules/BreakdownOfLeavesCard/index.tsx, client/src/components/molecules/LeaveManagementResultTable/Table.tsx, client/src/components/molecules/LeaveManagementResultTable/columns.tsx, client/src/components/molecules/LeaveManagementResultTable/index.tsx, client/src/graphql/queries/leaveQuery.ts, client/src/hooks/useLeave.ts, client/src/pages/leave-management/leave-summary.tsx, client/src/pages/leave-management/yearly-summary.tsx, client/src/pages/my-leaves.tsx, client/src/utils/constants/leaveTypes.ts, client/src/utils/generateData.ts, client/src/utils/getLeaveType.ts, client/src/utils/types/leaveTypes.ts
https://framgiaph.backlog.com/view/HRIS-85
- Please populate the leaves table
- You may access the page in `http://localhost:3000/my-leaves`
- go to `http://localhost:3000/my-leaves`
It should be able to display the heatmap, list of leaves and breakdown of leaves
https://user-images.githubusercontent.com/110364637/216516292-a6099398-a649-4166-b492-a877bbe7e89f.mp4
=> HRIS-85 [FE] Integrate Fetch Leave Data for the in My Leaves Page functionality

client/src/components/molecules/LeaveManagementResultTable/index.tsx, client/src/components/molecules/SummaryFilterDropdown/index.tsx, client/src/hooks/useLeave.ts, client/src/pages/my-leaves.tsx
https://framgiaph.backlog.com/view/HRIS-87
- access http://localhost:3000/my-leaves
- It should be able to filter leaves by year
https://user-images.githubusercontent.com/110364637/216863172-69e759f1-2d21-4cd1-aa57-d099142a2c2d.mp4
=> HRIS-87 [FE] Implement and Integrate filter functionality in my leaves page

api/Program.cs, api/Requests/CreateLeaveRequest.cs, api/Schema/Queries/LeaveQuery.cs, api/Schema/Queries/UserQuery.cs, api/Services/LeaveService.cs, api/Services/UserService.cs, client/package-lock.json, client/src/components/molecules/AddNewLeaveModal/LeaveTab.tsx, client/src/components/molecules/AddNewLeaveModal/UndertimeTab.tsx, client/src/graphql/mutations/leaveMutation.ts, client/src/graphql/queries/UserQuery.ts, client/src/graphql/queries/leaveQuery.ts, client/src/graphql/queries/projectQuery.ts, client/src/hooks/useLeave.ts, client/src/hooks/useProject.ts, client/src/hooks/useUserQuery.ts, client/src/utils/constants/roles.ts, client/src/utils/createLeaveHelpers.ts, client/src/utils/types/formValues.ts, client/src/utils/types/leaveTypes.ts, client/src/utils/types/projectTypes.ts
https://framgiaph.backlog.com/view/HRIS-81
- You may access the page in http://localhost:3000/my-leaves?year=2023
- go to http://localhost:3000/my-leaves?year=2023
- Click the File Request modal
It should be able to file leave an undertime request  successfully and automatically updates the summary on heatmap, table and breakdown
https://user-images.githubusercontent.com/110364637/216946628-77ea1aeb-dfbe-41b2-a762-097e8683ff98.mp4
=> HRIS-81 [FE] Integrate File Leave Request Functionality

client/src/pages/leave-management/leave-summary.tsx
https://framgiaph.backlog.com/view/HRIS-101
- Revision 01 of task HRIS-101
- go to `http://localhost:3000/leave-management/leave-summary`
- On first visit of the page, it should display leave summary of the current logged-in user
[InitialData.webm](https://user-images.githubusercontent.com/111718037/217193393-584cf83d-c997-4d5f-9315-704f7e538f08.webm)
=> HRIS-101-01 [FE] Add initial data in Leave Summary page

client/src/components/templates/LeaveManagementLayout/index.tsx, client/src/pages/leave-management/list-of-leave.tsx
- https://framgiaph.backlog.com/view/HRIS-107
N/A
goto `/leave-management/list-of-leave` page to see the result
- Able to search in the List of Leave Page 
[bugtask in leave.webm](https://user-images.githubusercontent.com/108642414/217511833-01161e80-17c0-43ec-b436-c6aa0f82ed49.webm)
=> HRIS-107 [BugTask] Remove Filter markup and implement search function

api/DTOs/UserDTO.cs, api/Program.cs, api/Services/HttpContextService.cs, api/Services/TimeInService.cs
https://framgiaph.backlog.com/view/HRIS-102
- important to test in docker
- login or go to `http://localhost:3000/`
- the avatar images should now work properly when the app is running in docker
=> HRIS-102-01 [BE] Fix: Modified avatarLink generation to work on docker

client/src/components/molecules/MyOvertimeTable/Chip.tsx, client/src/components/molecules/MyOvertimeTable/DesktopTable.tsx, client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx, client/src/components/molecules/MyOvertimeTable/ShowRemarksModal.tsx, client/src/components/molecules/MyOvertimeTable/YearlyFilterDropdown.tsx, client/src/components/molecules/MyOvertimeTable/columns.tsx, client/src/components/molecules/MyOvertimeTable/index.tsx, client/src/components/templates/ModalTemplate/ModalHeader.tsx, client/src/pages/my-overtime.tsx, client/src/utils/constants/dummyAddNewLeaveFields.ts, client/src/utils/constants/dummyMyOvertimeData.ts, client/src/utils/constants/overtimeStatus.ts, client/src/utils/interfaces/index.tsx, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
- https://framgiaph.backlog.com/view/HRIS-103
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=2741%3A20205&t=ps80W4iqx3v6xAhM-4
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=2741%3A20833&t=ps80W4iqx3v6xAhM-4
- cd client && npm run dev
- Go to the `/my-overtime` route page
- It should now have the markup for My Overtime Page
- Responsive from Desktop to Mobile Design
[my overtime page.webm](https://user-images.githubusercontent.com/108642414/217497885-0a9aae92-8237-4553-b03a-24cfb25c6aa2.webm)
=> HRIS-103 [Markup] Create My Overtime Page

client/src/components/molecules/NavList/index.tsx, client/src/components/molecules/OvertimeManagementTable/ApproveConfirmationModal.tsx, client/src/components/molecules/OvertimeManagementTable/DesktopTable.tsx, client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx, client/src/components/molecules/OvertimeManagementTable/ShowRemarksModal.tsx, client/src/components/molecules/OvertimeManagementTable/UpdateOvertimeModal.tsx, client/src/components/molecules/OvertimeManagementTable/columns.tsx, client/src/components/molecules/OvertimeManagementTable/index.tsx, client/src/components/organisms/Header/index.tsx, client/src/pages/overtime-management.tsx, client/src/utils/constants/dummyOvertimeManagementData.ts, client/src/utils/constants/sidebarMenu.ts, client/src/utils/interfaces/index.tsx, client/src/utils/styles/tailwind.css
- https://framgiaph.backlog.com/view/HRIS-106
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=2576%3A22180&t=vtIKorIP8VTXRNaC-4
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=2576%3A23541&t=vtIKorIP8VTXRNaC-4
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=2576%3A22968&t=vtIKorIP8VTXRNaC-4
cd api && dotnet run watch
- It should specifically show the sidebar content based on the user role
- Responsive design from mobile to desktop
- Fixed types and rendered specific data
=> HRIS-106 [Markup] Create Overtime Management Page for Manager

client/src/components/molecules/AddNewLeaveModal/LeaveTab.tsx, client/src/components/molecules/AddNewLeaveModal/UndertimeTab.tsx, client/src/components/molecules/AddNewLeaveModal/index.tsx, client/src/components/molecules/OvertimeManagementTable/columns.tsx, client/src/utils/constants/dummyAddNewLeaveFields.ts, client/src/utils/constants/leaveTypes.ts, client/src/utils/constants/numberOfDaysInLeaves.ts, client/src/utils/createLeaveHelpers.ts, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
- https://framgiaph.backlog.com/view/HRIS-124
- All the field of select are now in react-select package
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=3106%3A20695&t=N9fQqjoGoDCYIAVT-4
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=3106%3A20523&t=N9fQqjoGoDCYIAVT-4
cd api && dotnet run watch
It should now have the newly updated markup for filing Leave/Undertime Request Modal
Applied react-hook-form
[modified.webm](https://user-images.githubusercontent.com/108642414/219319994-d29ae35e-5c77-431f-b1c4-e5eb0805a1b2.webm)
=> HRIS-124 [Markup] Modify File Leave/Undertime Request Modal

client/src/components/molecules/EmployeeManagementTable/DesktopTable.tsx, client/src/components/molecules/EmployeeManagementTable/MobileDisclose.tsx, client/src/components/molecules/EmployeeManagementTable/columns.tsx, client/src/components/molecules/EmployeeManagementTable/index.tsx, client/src/pages/employee-management.tsx, client/src/utils/constants/dummyEmployeeManagement.ts, client/src/utils/interfaces/index.tsx
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-126&category=342155&assignee=405757)
cd client
npm run dev
or 
run docker
It should allow HR Admins to view the list of employees and manage their information.
Desktop View
Mobile View
Mobile View 2
=> HRIS-126 [Markup] Create Employee Management Page

api/Enums/InputValidationMessageEnum.cs, api/Requests/CreateLeaveRequest.cs, api/Services/LeaveService.cs, api/Services/NotificationService.cs, api/Utils/Validation.cs, client/package-lock.json, client/package.json, client/src/components/molecules/AddNewLeaveModal/LeaveTab.tsx, client/src/components/molecules/AddNewLeaveModal/UndertimeTab.tsx, client/src/components/organisms/Header/index.tsx, client/src/graphql/subscriptions/leaveSubscription.ts, client/src/pages/sign-in.tsx, client/src/utils/constants/dummyAddNewLeaveFields.ts, client/src/utils/createLeaveHelpers.ts, client/src/utils/types/formValues.ts, client/src/utils/types/leaveTypes.ts
https://framgiaph.backlog.com/view/HRIS-122
- You need to re-login to check this feature
- To test the real-time notification on the FE, you can set your own role to `Manager` or `ProjectLeader` in the database. Then file leave using the form selecting yourself as manager or project leader.
- Or you can create leave request in the graphql playground using this mutation
```
mutation($leave: CreateLeaveRequestInput!){
createLeave(leave: $leave){
id
}
}
```
- with variables (change `managerId` or `projectLeaderId` to your own user id)
```
{
"leave": {
"userId": 4,
"leaveTypeId": 3,
"managerId": 70,
"otherProject": "",
"reason": "qweqwe",
"leaveDates": [
{
"leaveDate": "2023-02-17",
"isWithPay": true,
"days": 0.625
}
],
"leaveProjects": [
{
"projectId": 1,
"projectLeaderId": 4
},
{ …
```
=> HRIS-122 [FE] Integrate Send notification when filing a leave request functionality

api/DTOs/FileDTO.cs, api/DTOs/SpecificTimeDTO.cs, api/Program.cs, api/Schema/Queries/TimeSheetQuery.cs, api/Services/TimeSheetService.cs, client/src/components/organisms/ViewDetailsDrawer/index.tsx, client/src/graphql/queries/timesheetQueries.ts, client/src/utils/types/timeEntryTypes.ts
https://framgiaph.backlog.com/view/HRIS-100
- N/A
- in the root directory run ``` docker compose up --build ```
- It should do a direct download functionality in a docker environment setup
https://user-images.githubusercontent.com/109492180/220248173-334171d6-cc37-4932-8fc5-0aaf2df1a400.mp4
=> HRIS-100-01 [FE] Fix: Download button functionality

client/src/components/molecules/AddNewEmployeeModal/index.tsx, client/src/pages/employee-management.tsx, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-127&category=342155&assignee=405757)
npm run dev 
or
docker compose up
Upon clicking the Add New Employee button, the Add New Employe Modal shall popup and allow the user to create a new employee.
Employee Modal (Desktop)
Employee Modal Input (Desktop)
Employee Modal Validation (Desktop)
Employee Modal (Mobile)
=> HRIS-127 [Markup] Create Add Employee Modal

api/Services/LeaveService.cs, api/Services/NotificationService.cs, api/Services/UserService.cs, client/src/components/molecules/NotificationList/NotificationItem.tsx, client/src/components/organisms/Header/index.tsx, client/src/graphql/queries/NotificationQueries.ts, client/src/graphql/queries/leaveQueries.ts, client/src/hooks/useNotificationQuery.ts, client/src/pages/leave-management/list-of-leave.tsx, client/src/pages/notifications.tsx, client/src/utils/constants/dummyNotificationData.ts, client/src/utils/constants/notificationTypes.ts, client/src/utils/interfaces/index.tsx, client/src/utils/types/leaveTypes.ts, client/src/utils/types/notificationTypes.ts
https://framgiaph.backlog.com/view/HRIS-123
- Previous leave/notification data in the database will not work
- Also fixed the fetching in the `List of Leave` page
- go to `http://localhost:3000/` or any other page
- click the bell/notification icon in the header, then click the `See all notifications` button
- Clicking the notification icon will redirect the user to notification page
- Unread notifications will be highlighted
- Notification page will automatically update when receiving new notification
[Notification.webm](https://user-images.githubusercontent.com/111718037/221461997-36c964e2-ef37-439b-a72d-062326a6249f.webm)
=> HRIS-123 [FE] Implement Fetch notifications for the authenticated user functionality

client/src/components/molecules/AddNewOvertimeModal/index.tsx, client/src/components/molecules/LegendTooltip/index.tsx, client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx, client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx, client/src/components/molecules/OvertimeManagementTable/ApproveConfirmationModal.tsx, client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx, client/src/components/molecules/OvertimeManagementTable/UpdateOvertimeModal.tsx, client/src/components/molecules/OvertimeManagementTable/columns.tsx, client/src/pages/my-overtime.tsx, client/src/utils/constants/dummyOvertimeManagementData.ts, client/src/utils/interfaces/index.tsx, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
https://framgiaph.backlog.com/view/HRIS-104
- This is revision of #104 
cd `client` && `npm run dev`
cd `api` && `dotnet run watch`
- It should now have an updated modal for filing Overtime 
[Sun_ HRIS - My Daily Time Record.webm](https://user-images.githubusercontent.com/108642414/222348066-22e57e5f-5774-4bdf-a04d-5055e7ffc68b.webm)
=> HRIS-104-01 [Markup] Update File for Overtime Modal

api/Context/HrisContext.cs, api/Entities/MultiProject.cs, api/Entities/Overtime.cs, api/Entities/OvertimeNotification.cs, api/Entities/User.cs, api/Enums/ErrorMessageEnum.cs, api/Enums/MultiProjectType.cs, api/Migrations/20230302040253_Overtime_LeaveProjectToMultiProject.Designer.cs, api/Migrations/20230302040253_Overtime_LeaveProjectToMultiProject.cs, api/Program.cs, api/Requests/CreateLeaveRequest.cs, api/Requests/CreateOvertimeRequest.cs, api/Requests/LeaveProjectRequest.cs, api/Schema/Mutations/LeaveMutation.cs, api/Schema/Mutations/OvertimeMutation.cs, api/Seeders/DatabaseSeeder.cs, api/Services/LeaveService.cs, api/Services/NotificationService.cs, api/Services/OvertimeService.cs, api/Subscriptions/SubscriptionObjectType.cs, api/Utils/Validation.cs, client/src/pages/leave-management/list-of-leave.tsx
https://framgiaph.backlog.com/view/HRIS-135
https://framgiaph.backlog.com/view/HRIS-137
- Fix for HRIS-137 is also included in this PR
- run `dotnet ef database update` on `api` directory
- to create overtime request, you can run this mutation
```
mutation($overtime: CreateOvertimeRequestInput!){
createOvertime(overtime: $overtime){
id
}
}
```
```
{
"overtime": {
"userId": 4,
"managerId": 70,
"otherProject": "hris",
"requestedMinutes": 121,
"remarks": "testing",
"date": "2023-03-01",
"overtimeProjects": [
{
"projectId": 2,
"projectLeaderId": 4
},
{
"projectId": 3,
"projectLeaderId": 2
}
]
}
}
```
- to receive notification, you can run this subscription then create overtime request
```
subscription { …
```
=> HRIS-135 [BE] Implement File Overtime request functionality

client/src/pages/my-forms/personal-information.tsx, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-129)
Optional
npm i
npm run dev
or run docker
Route links
Etc
- Allow user to fill up the Personal Information Form
Desktop View
Desktop View with Required Errors
Mobile View with Required Errors
=> HRIS-129 [Markup] Create Personal Information Form

client/src/pages/my-forms/personal-information.tsx, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-129#comment-139029044)
git pull
cd client
npm run dev
http://localhost:3000/my-forms/personal-information
Users are prompted when government credentials are not correct. Added validations for government IDs
=> HRIS-129-1 [Markup] Personal Form Government Validations

api/DTOs/OvertimeDTO.cs, api/Services/ApprovalService.cs, client/src/components/molecules/AddNewOvertimeModal/index.tsx, client/src/components/molecules/OvertimeManagementTable/ApproveConfirmationModal.tsx, client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx, client/src/components/molecules/OvertimeManagementTable/UpdateOvertimeModal.tsx, client/src/components/molecules/OvertimeManagementTable/columns.tsx, client/src/hooks/useOvertime.ts, client/src/pages/overtime-management.tsx, client/src/utils/constants/dummyOvertimeManagementData.ts, client/src/utils/interfaces/index.tsx, client/src/utils/validation/index.ts
https://framgiaph.backlog.com/view/HRIS-148
- login as Manager and go to `http://localhost:3000/overtime-management`
- Manager should be able to approve/disapprove overtime request
[approve.webm](https://user-images.githubusercontent.com/111718037/224619130-e6ac3e50-78ec-43ab-b5db-f0152ef14ea5.webm)
[disapprove.webm](https://user-images.githubusercontent.com/111718037/224619150-76c19011-84f3-4855-ba1b-6a22cedd16bc.webm)
=> HRIS-148 [FE] Integrate approve and disapprove requested overtime for manager functionality

client/src/components/molecules/OvertimeManagementTable/columns.tsx
https://framgiaph.backlog.com/view/HRIS-151
- Fix only
- In the root directory run ``` docker compose up --build ```
- If others is selected or user type the value fetch only the input value inside the dropdown menu
https://user-images.githubusercontent.com/109492180/224657757-73485dd7-b1db-4d4b-a085-95e56efb7b07.mp4
=> HRIS-151/HRIS-153-01 [BE/FE] Fix overtime management table.

client/src/components/molecules/DTRSummaryTable/DesktopTable.tsx, client/src/components/molecules/MyDailyTimeRecordTable/DesktopTable.tsx, client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx, client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
https://framgiaph.backlog.com/view/HRIS-160
- If Project Leader approved and Manager Disapproved the icon displayed should be `Disapproved` in My DTR table
- DTR Summary Table should not sideways scrollable
=> HRIS-160-01 [BE/FE] Fix Overtime Icon display and Scroll in Summary table

client/src/pages/my-forms/atm-applications.tsx, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-130)
run docker or cd client and then npm run dev
Visit http://localhost:3000/my-forms/atm-applications
Users can fill up the ATM Application Form and submit it.
Desktop View
Mobile View
=> HRIS-130 [Markup] Create ATM Application Form

client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx, client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
https://framgiaph.backlog.com/view/HRIS-162
- go to MyDTR page
- If there is no `TimeOut` for a specific time entry, it shouldn't compute for overtime minutes
=> HRIS-162 [BugTask] Fix: Error in My DTR status of overtime column

client/src/components/atoms/Buttons/DayButton.tsx, client/src/pages/my-forms/atm-applications.tsx, client/src/pages/my-forms/personal-information.tsx, client/src/pages/schedule-management.tsx
- https://framgiaph.backlog.com/view/HRIS-132
This is revision task of #111 
- cd client && npm run dev
- cd api && dotnet run watch
It should now have a responsive design based on the comment of sir Paul
=> HRIS-132-01 [Markup] Fix Mobile View Schedule Form, Move the buttons in the center

client/src/pages/my-forms/laptop-monitoring.tsx, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-131)
npm run dev or run docker
It should allow users to fill up their laptop monitoring form
Desktop View
=> HRIS-131 [Markup] Create Laptop Monitoring Form

client/src/components/molecules/MyDailyTimeRecordTable/ChangeShiftRequestModal.tsx, client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-166)
npm run dev or run docker
Go to `my-daily-time-record` page
Click on the action column
Click on Change offset
It should allow users to file change shift schedule through the modal
=> HRIS-166 [Markup] Create Modal for Change Shift Request

api/DTOs/UserDTO.cs, api/Enums/InputValidationMessageEnum.cs, api/Requests/CreateChangeShiftRequest.cs, api/Services/ChangeShiftService.cs, api/Services/TimeInService.cs, api/Utils/Validation.cs, client/src/components/molecules/MyDailyTimeRecordTable/ChangeShiftRequestModal.tsx, client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx, client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx, client/src/graphql/mutations/changeShiftMutation.ts, client/src/graphql/queries/UserQuery.ts, client/src/hooks/useChangeShift.ts, client/src/utils/constants/projects.ts, client/src/utils/constants/userPositions.ts, client/src/utils/types/changeShiftTypes.ts, client/src/utils/types/userTypes.ts
https://framgiaph.backlog.com/view/HRIS-164
- go to MyDTR and click `Actions` then `Change Shift Request`
- The `Change Shift Request` button should only be visible to Non-ESL users
- User can only request once per time entries.
- There would be alert for fail/success
[ChangeShift.webm](https://user-images.githubusercontent.com/111718037/227455685-be665a6d-d2db-4579-b7a8-5daf4cac5d33.webm)
=> HRIS-164 [FE] Integrate request for change shift functionality

client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx, client/src/utils/types/userTypes.ts
https://framgiaph.backlog.com/view/HRIS-164
- also fixed type declaration in `userTypes.ts`
- go to `http://localhost:3000/my-daily-time-record`
- User can now properly use space key in text area in change shift modal and offset modal in MyDTR
[spaceFix.webm](https://user-images.githubusercontent.com/111718037/227876457-220cf043-9cba-4c76-b042-b3ffe41d2383.webm)
=> HRIS-164-01 Fix space key in Textarea

client/src/components/molecules/FiledOffsetModal/FileOffsetModal.tsx, client/src/components/molecules/FiledOffsetModal/index.tsx, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-168)
npm run dev
go to http://localhost:3000/my-daily-time-record
make sure current user's position is set to esl teacher or (5) in Table plus
click the actions button on the table
click the filed offset
click file request
the modal should pop up
ESL Teachers can file offset request through the modal
Desktop view
Mobile view
=> HRIS-168 [Markup] Create Modal for filing a request for OT or Offset

api/Services/ApprovalService.cs, client/src/components/molecules/NotificationList/ViewDetailsModal.tsx, client/src/components/organisms/Header/index.tsx, client/src/graphql/mutations/changeShiftMutation.ts, client/src/graphql/subscriptions/leaveSubscription.ts, client/src/hooks/useChangeShift.ts, client/src/pages/notifications.tsx, client/src/utils/constants/dummyNotificationData.ts, client/src/utils/constants/notificationTypes.ts, client/src/utils/interfaces/index.tsx, client/src/utils/types/changeShiftTypes.ts, client/src/utils/types/notificationTypes.ts
https://framgiaph.backlog.com/view/HRIS-175
- you might need to open at least 3 accounts (non-esl` user, project leader, manager)
- (Non-ESL user)go to MyDTR and click `Change Shift Request` button in the `Actions` column
- (Leader/Manager) Click notification bell and click specific notification.
- (Leader/Manager) Click Approve/Disapprove from the modal
- After Non-ESL user created request, Project Leader should receive notification
- After Project Leader approved request, Manager should receive notification
- After Manager approved request, requesting user should receive notification
[ApproveDisapproveChangeShiftFE.webm](https://user-images.githubusercontent.com/111718037/228451281-925578d0-d2b8-456c-aa85-067bce0614e0.webm)
=> HRIS-175 [FE] Integrate approve or disapprove change shift request functionality

api/Context/HrisContext.cs, api/Entities/ESLChangeShiftNotification.cs, api/Entities/ESLChangeShiftRequest.cs, api/Enums/InputValidationMessageEnum.cs, api/Enums/NotificationTypeEnum.cs, api/Migrations/20230330070738_AddESLChangeShift.Designer.cs, api/Migrations/20230330070738_AddESLChangeShift.cs, api/NotificationDataClasses/ChangeShiftData.cs, api/Program.cs, api/Requests/CreateESLChangeShiftRequest.cs, api/Schema/Mutations/ESLChangeShiftMutation.cs, api/Schema/Queries/UserQuery.cs, api/Services/ESLChangeShiftService.cs, api/Services/NotificationService.cs, api/Services/UserService.cs, api/Subscriptions/SubscriptionObjectType.cs, api/Utils/Validation.cs
https://framgiaph.backlog.com/view/HRIS-181
- I used the table name `ESLChangeShiftRequests` for this feature because it functions very similar to the previously implemented Change Shift, but still open for suggestions.
- I included in this task a query for fetching all ESL Users for future integration
- run `dotnet ef database update` in `api` directory
- to create request, use the following mutation
```
mutation ($request: CreateESLChangeShiftRequestInput!) {
createESLChangeShift(request: $request){
id
}
}
{
"request": {
"userId" : 4,
"teamLeaderId" : 3,
"timeEntryId" : 4,
"timeIn" : "09:00",
"timeOut" : "14:00",
"description" : "test description"
}
}
```
- to monitor the notification sent, use the following …
=> HRIS-181 [BE] Implement change schedule as an offset functionality for ESL Teacher

api/Services/NotificationService.cs, client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
https://framgiaph.backlog.com/view/HRIS-175
- Revision PR of #145 
- Must create new notifications
- go to Notification page and open a `Change Shift` notification
- The Date should be the date of Time Entry
=> HRIS-175-01 Fix Date in Notification Detail Modal

client/src/components/molecules/FiledOffsetModal/FileOffsetModal.tsx, client/src/components/molecules/MyDailyTimeRecordTable/AddNewOffsetModal.tsx, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-168#comment-142255036)
npm run dev
go to http://localhost:3000/my-daily-time-record
make sure current user's position is set to esl teacher or (5) in Table plus
click the actions button on the table
click the filed offset
click file request
the modal should pop up
Users can now see red border upon error message of AddNewOffsetModal and FileOffsetModal
FileOffsetModal
AddNewOffsetModal
=> HRIS-168-1 [Markup] Bugfix on AddNewOffsetModal and FileOffsetModal border error

api/Context/HrisContext.cs, api/Entities/ESLOffset.cs, api/Entities/ESLOffsetNotification.cs, api/Entities/TimeEntry.cs, api/Enums/NotificationTypeEnum.cs, api/Migrations/20230331054345_AddESLOffset.Designer.cs, api/Migrations/20230331054345_AddESLOffset.cs, api/Program.cs, api/Requests/CreateESLOffsetRequest.cs, api/Schema/Mutations/ESLOffsetMutation.cs, api/Schema/Queries/ChangeShiftQuery.cs, api/Schema/Queries/ESLChangeShiftQuery.cs, api/Schema/Queries/ESLOffsetQuery.cs, api/Services/ChangeShiftService.cs, api/Services/ESLOffsetService.cs, api/Services/NotificationService.cs, api/Subscriptions/SubscriptionObjectType.cs, api/Utils/Validation.cs
https://framgiaph.backlog.com/view/HRIS-170
- Also created queries `eslOffsetsByTimeEntry`, `eslChangeShiftByTimeEntry`, and `changeShiftByTimeEntry` for future integrations
- run `dotnet ef database update` in `api` directory
- to create requests, run the following mutation
```
mutation ($request: CreateESLOffsetRequestInput!) {
createESLOffset(request: $request){
id
}
}
{
"request": {
"userId" : 4,
"teamLeaderId" : 3,
"timeEntryId" : 4,
"timeIn" : "09:00",
"timeOut" : "14:00",
"description" : "test description",
"title": "title 2"
}
}
```
- to monitor the notification sent, use the following subscription
```
subscription {
eslOffsetCreated(id: 3) {
id
type
data
readAt
isRead
}
}
```
- to query …
=> HRIS-170 [BE] Implement file OT or offset request functionality

api/DTOs/ESLOffsetDTO.cs, api/Enums/NotificationTypeEnum.cs, api/Schema/Queries/ESLOffsetQuery.cs, api/Services/ESLOffsetService.cs, client/src/components/molecules/FiledOffsetModal/FileOffsetModal.tsx, client/src/components/molecules/FiledOffsetModal/MobileDisclose.tsx, client/src/components/molecules/FiledOffsetModal/columns.tsx, client/src/components/molecules/FiledOffsetModal/index.tsx, client/src/components/molecules/MyDailyTimeRecordTable/AddNewOffsetModal.tsx, client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx, client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx, client/src/components/molecules/NotificationList/NotificationTypeDetails/OffsetDetails.tsx, client/src/components/molecules/NotificationList/ViewDetailsModal.tsx, client/src/components/organisms/Header/index.tsx, client/src/graphql/mutations/fileOffsetMutation.ts, client/src/graphql/queries/eslFiledOffsets.ts, client/src/graphql/subscriptions/fileOffsetSubscription.ts, client/src/hooks/useFileOffset.ts, client/src/hooks/useOffsetForESL.ts, client/src/lib/queryClient.ts, client/src/pages/_app.tsx, client/src/pages/sign-in.tsx, client/src/utils/constants/dummyFiledOffsetsData.ts, client/src/utils/constants/notificationTypes.ts, client/src/utils/icons/WaveStyle.tsx, client/src/utils/interfaces/fileOffsetInterface.ts, client/src/utils/interfaces/index.tsx, client/src/utils/myDailyTimeHelpers.ts
https://framgiaph.backlog.com/view/HRIS-183
#151 
Change the notification type of ESL change shift
- ESL User can now be able to file an offset request
- Can view the offsets data requested in the modal
- The team leader will be notify when there is new offset request
[filing.webm](https://user-images.githubusercontent.com/108642414/229963387-6c4b3bf4-4beb-4a3e-8e7a-510d41530cb5.webm)
=> HRIS-183 [FE] Integrate file OT or offset request functionality

client/src/pages/sign-in.tsx
https://framgiaph.backlog.com/view/HRIS-185
- Improvements only
- in the root directory, run ``` docker compose up --build ```
- During verification window, button should display the pulse loader animation
https://user-images.githubusercontent.com/109492180/230039641-716d9958-52e5-4484-a4e5-eafd0af2a4d1.mp4
=> HRIS-185 [FE] Improve the Login button

client/src/components/templates/ScheduleManagementLayout/index.tsx, client/src/graphql/queries/employeeSchedule.ts, client/src/hooks/useEmployeeSchedule.ts, client/src/pages/schedule-management.tsx, client/src/utils/types/employeeScheduleTypes.ts
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-198)
run docker
make sure you have an existing schedule in your table. 
Your existing schedules in your table should be viewed on this page.
It should allow HR Admins can view schedule functionality
Desktop View
Desktop Recording
[screen-capture.webm](https://user-images.githubusercontent.com/109579325/232436422-82aa1b47-40a6-46fe-b03e-46227c3920ad.webm)
=> HRIS-198 [FE] Integrate display schedule functionality

client/src/pages/schedule-management.tsx, client/src/utils/constants/weekDays.ts, client/src/utils/types/weekDayTypes.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-198#comment-144744821)
run docker
It should fix the issue/bug, where creating a new day always starts on a Monday.
Proof
[screen-capture.webm](https://user-images.githubusercontent.com/109579325/232644912-9ee4c532-9699-44ad-876c-3cd2cdc8c593.webm)
=> HRIS-198-1 [FE] Bugfix on new day always starts on monday

client/src/graphql/mutations/employeeScheduleMutation.ts, client/src/hooks/useEmployeeSchedule.ts, client/src/pages/schedule-management.tsx, client/src/utils/constants/weekDays.ts, client/src/utils/types/employeeScheduleTypes.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-194)
run docker
create a schedule. You may follow the video attached below to see how to create one.
It should allow HR Admins to create new Employee Schedule
Proof
[screen-capture.webm](https://user-images.githubusercontent.com/109579325/232946789-6b96fa28-4c2f-43ec-be98-5667643f489e.webm)
=> HRIS-194 [FE] Integrate Create Employee Schedule Functionality

client/src/pages/dtr-management.tsx
https://framgiaph.backlog.com/view/HRIS-201
- open console panel (F12)
- go to any page then click `DTR Management` from the sidebar
- There should be no more error message in the console panel when visiting DTR Management page
[DTRManagementConsole.webm](https://user-images.githubusercontent.com/111718037/233019367-4e0bdb01-6e81-4ee0-be22-6de81f2509de.webm)
=> HRIS-201 [FE] Remove Error in DTRManagement Page Console

client/src/graphql/mutations/employeeScheduleMutation.ts, client/src/hooks/useEmployeeSchedule.ts, client/src/pages/schedule-management.tsx, client/src/utils/types/employeeScheduleTypes.ts
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-196)
Run docker
edit an existing schedule
HR Admins can update/edit existing employee schedule
Proof
[screen-capture.webm](https://user-images.githubusercontent.com/109579325/233239270-3d6b3033-ce9d-4f23-8eca-55e44a7a1e19.webm)
=> HRIS-196 [FE] Integrate edit schedule functionality

client/src/pages/schedule-management.tsx
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-196#comment-145305108)
Run docker
edit a schedule
press cancel
It should allow users to cancel editing schedule
Proof
[screen-capture.webm](https://user-images.githubusercontent.com/109579325/233338667-50f7ca08-8124-490d-aaf2-e9d61bcec60d.webm)
=> HRIS-196-1 [FE] Allow Edit Cancel

api/DTOs/UserDTO.cs, api/Schema/Queries/EmployeeScheduleQuery.cs, api/Services/EmployeeScheduleService.cs
https://framgiaph.backlog.com/view/HRIS-209
- run `docker compose up --build` or `dotnet run`
- run the following query
```
query () {
employeesBySchedule (employeeScheduleId: 1) {
name
avatarLink
position{
name
}
isOnline
}
}
```
- The query should return list of employees in a specific schedule
- Sample query result
=> HRIS-209 [BE] Develop API endpoint to retrieve all employees assigned to a specified schedule

client/src/components/molecules/ViewScheduleMembersModal/AddScheduleMembersModal.tsx, client/src/components/molecules/ViewScheduleMembersModal/index.tsx, client/src/components/templates/ModalTemplate/ModalHeader.tsx, client/src/utils/helpers/scheduleMemberHelpers.ts, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
- https://framgiaph.backlog.com/view/HRIS-211
Figma design
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=4386-30082&t=jhFnYMvC5XGJg7j5-4
- We removed the avatar due to some problem error issue in react-select package. So for now we don't have avatar
- I still didn't change the figma design for some reference and improvement in to future
- It should now have a Markup for Adding Employees to a schedule Modal
[add memebers schedule.webm](https://user-images.githubusercontent.com/108642414/234227833-cee20baa-0884-4090-8651-a16ac8b64fae.webm)
=> HRIS-211 [Markup] Create Modal for adding employees to a schedule

client/src/components/molecules/ViewScheduleMembersModal/MemberList.tsx, client/src/components/molecules/ViewScheduleMembersModal/ReassignMemberScheduleModal.tsx, client/src/components/templates/ModalTemplate/ModalHeader.tsx, client/src/components/templates/ScheduleManagementLayout/index.tsx, client/src/graphql/queries/employeeSchedule.ts, client/src/pages/schedule-management.tsx, client/src/utils/helpers/scheduleMemberHelpers.ts, client/src/utils/types/employeeScheduleTypes.ts, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
- https://framgiaph.backlog.com/view/HRIS-216
- Figma design
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=4427-24019&t=xwRi6fR5xZsMd4kF-4
- goto `/schedule-management` page
- It should now have a Reassign Modal for every Member in the Schedule
[mdoal.webm](https://user-images.githubusercontent.com/108642414/234477331-9ddca0e5-4d61-47e5-abb7-673c5ce1ac36.webm)
[skeletong and delete.webm](https://user-images.githubusercontent.com/108642414/234493686-fa17b0d8-73f4-49ce-a3f9-2ccfad124f95.webm)
=> HRIS-216 [Markup] Create Modal for Re-assigning an employee

api/Enums/ErrorMessageEnum.cs, api/Enums/InputValidationMessageEnum.cs, api/Enums/SuccessMessageEnum.cs, api/Requests/AddMemberToScheduleRequest.cs, api/Schema/Mutations/EmployeeScheduleMutation.cs, api/Services/EmployeeScheduleService.cs, api/Utils/Validation.cs
https://framgiaph.backlog.com/view/HRIS-214
- To test run the following mutation:
```
mutation ($request: AddMemberToScheduleRequestInput!) {
addMembersToSchedule(request: $request)
}
```
```
{
"request": {
"userId": 57,
"employeeIds": [38, 39, 40, 47],
"scheduleId": 1001
}
}
```
- It should check if the:
- user is an HR admin
- schedule exists
- employee exists
- employee is not in the shcedule
- It should change the scheduleId of the employee to the desired schedule
https://user-images.githubusercontent.com/109492180/234465155-849873c8-9cd6-4dae-9f42-085e4855fa2a.mp4
=> HRIS-214 [BE] Implement add member to schedule functionality

client/src/components/templates/ScheduleManagementLayout/index.tsx, client/src/graphql/mutations/employeeScheduleMutation.ts, client/src/hooks/useEmployeeSchedule.ts, client/src/utils/types/employeeScheduleTypes.ts
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-223)
run docker
Users can delete a schedule
Users cannot delete a schedule that has employees under it
Proof:
[screen-capture.webm](https://user-images.githubusercontent.com/109579325/234832966-f226acf7-a719-4a63-a8d8-63d07d750385.webm)
=> HRIS-223 [FE] Integrate remove schedule functionality

api/Enums/SuccessMessageEnum.cs, client/src/components/molecules/ViewScheduleMembersModal/AddScheduleMembersModal.tsx, client/src/components/molecules/ViewScheduleMembersModal/index.tsx, client/src/graphql/mutations/employeeScheduleMutation.ts, client/src/graphql/queries/UserQuery.ts, client/src/hooks/useEmployeeSchedule.ts, client/src/utils/helpers/scheduleMemberHelpers.ts, client/src/utils/types/employeeScheduleTypes.ts, client/src/utils/types/userTypes.ts
https://framgiaph.backlog.com/view/HRIS-215
- Frontend integration
- In the root directory, run ``` docker compose up --build ```
- Go to ``` http://localhost:3000/schedule-management ```
- Try to add a member to a specific schedule
- It should add the memeber(s) chosen to the list of members on that schedule after hitting save
- It should update the list of members, and the counter for the list of members on that schedule
- It should return a message if the query encounters an error
- It should return a message if the query is successful
https://user-images.githubusercontent.com/109492180/234812879-16f17ae3-9fb3-4d8a-b043-64edf81038d3.mp4
https://user-images.githubusercontent.com/109492180/234813378-04c98acd-e1a0-4eb7-9d1f-32b60ba3a147.mp4 …
=> HRIS-215 [FE] Integrate add member to schedule functionality

client/src/components/molecules/ViewScheduleMembersModal/MemberList.tsx, client/src/components/molecules/ViewScheduleMembersModal/ReassignMemberScheduleModal.tsx, client/src/graphql/mutations/employeeScheduleMutation.ts, client/src/hooks/useEmployeeSchedule.ts, client/src/utils/types/employeeScheduleTypes.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-218)
run docker
go to `http://localhost:3000/schedule-management` and re-assign a member as shown in the video below.
Users can re-assign other members to another schedule
Proof:
[screen-capture (1).webm](https://user-images.githubusercontent.com/109579325/235092743-9161f513-18ec-4333-8ead-d6a6874d9134.webm)
=> HRIS-218 [FE] Integrate re-assign employee schedule functionality

api/Services/LeaveService.cs
https://framgiaph.backlog.com/view/HRIS-233
- None
- In the root directory run ``` docker compose up --build ```
- MyLeaves page heatmap should only reflect approved leaves
https://user-images.githubusercontent.com/109492180/236400308-f186f5a9-7609-428b-ba01-f7bbfa66333f.mp4
=> HRIS-233 [Bugfix] Display Only Approved Leaves on All Leave Pages

client/src/components/organisms/Drawer/index.tsx, client/src/components/organisms/Sidebar/index.tsx, client/src/pages/my-forms/atm-applications.tsx, client/src/pages/my-forms/first-day-onboarding.tsx, client/src/pages/my-forms/laptop-monitoring.tsx, client/src/pages/my-forms/personal-information.tsx, client/src/utils/constants/sidebarMenu.ts
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-261)
If you want to run in `production` :
1. npm run build
2. npm start
If you want to run in `development`
1. npm run dev
1. Use the process.env.NODE_ENV to check whether the application is running on production or development
2. If the process.env.NODE_ENV is 'production' then it should not display the Forms
3. Also added where if the user manually inputs the link in production, it will display that the Forms page is under 
Production:
[screen-capture.webm](https://github.com/framgia/sph-hris/assets/109579325/329ab816-ff9c-40b1-9b79-7f73c21d1c09)
Development:
[screen-capture (1).webm](https://github.com/framgia/sph-hris/assets/109579325/f22e1d34-2f13-4c5f-9a2f-7581859ecad2)
=> HRIS-261 [FE] Hide Forms and Account Settings on the front-end.

api/DTOs/HeatMapDTO.cs, api/DTOs/LeaveBreakdownDTO.cs, api/DTOs/LeaveHeatMapDTO.cs, api/DTOs/LeavesTableDTO.cs, api/Enums/HeatmapValueEnum.cs, api/Services/LeaveService.cs, client/src/components/atoms/Chip/index.tsx, client/src/components/molecules/BreakdownOfLeavesCard/index.tsx, client/src/components/molecules/LeaveManagementResultTable/columns.tsx, client/src/graphql/queries/leaveQuery.ts, client/src/utils/constants/leaveStatus.ts, client/src/utils/generateData.ts, client/src/utils/types/leaveTypes.ts
https://framgiaph.backlog.com/view/HRIS-254
- Existing leave
- In the root directory run ``` docker compose up db api client -d ```
- Heatmap should only show the tooltip for pending requests
- New column for Status in the leave pages
- New row for Pending on Breakdown of Leaves in the leave pages
https://github.com/framgia/sph-hris/assets/109492180/3f944beb-823e-4a9d-9522-2d119833973e
=> HRIS-254 [FE/BE] Display all filed leaves, whether approved or not.

api/DTOs/TimeEntryDTO.cs
https://framgiaph.backlog.com/view/HRIS-273
- Previous PR #226
=> HRIS-273 [Bugfix] Modify TimeEntryDTO

api/DTOs/TimeEntryDTO.cs, api/Services/ApprovalService.cs, api/Services/TimeSheetService.cs, api/Utils/Validation.cs, client/src/components/atoms/IsUsedChip/index.tsx, client/src/components/molecules/FiledOffsetModal/columns.tsx, client/src/components/molecules/FiledOffsetModal/index.tsx, client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx, client/src/components/molecules/NotificationList/ViewDetailsModal/index.tsx, client/src/components/templates/DrawerTemplate/index.tsx, client/src/components/templates/ModalTemplate/index.tsx, client/src/graphql/queries/eslFiledOffsets.ts, client/src/graphql/queries/timesheetQueries.ts, client/src/utils/constants/dummyFiledOffsetsData.ts, client/src/utils/constants/isUsedStatus.ts, client/src/utils/interfaces/fileOffsetInterface.ts, client/src/utils/interfaces/index.tsx, client/src/utils/types/timeEntryTypes.ts
- https://framgiaph.backlog.com/view/HRIS-279
- None
- In the root directory run ``` docker compose up db api client -d ```
- In the filed offsets modal, it should reflect the isUsed status of the request
- It should reflect whether it is currently used or not by true or false
https://github.com/framgia/sph-hris/assets/109492180/3f5f41f2-0f22-4630-8ab7-3fda124350c0
=> HRIS-279 [BE/FE] Modify Filing for Offset functionality

api/Enums/InputValidationMessageEnum.cs, api/Services/TimeInService.cs, api/Utils/Validation/TimeInServiceInputValidation.cs, client/src/components/organisms/TimeInDrawer/index.tsx, client/src/components/organisms/TimeOutDrawer/index.tsx, client/src/utils/styles/globals.css
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-278)
run docker or npm run dev and dotnet watch
Notify users that they are required to answer the remarks section if timing in late.
Added the validation for backend when timing in.
Added extra code to check the bugs when timing out at the next day.
Proof:
[screen-capture.webm](https://github.com/framgia/sph-hris/assets/109579325/188021d8-6b8a-44c7-9c96-500c44d63c84)
=> HRIS-278 [BE/FE] Make Remarks Field Required for User Clock-In

api/DTOs/UserDTO.cs, api/Services/TimeSheetService.cs, client/src/components/molecules/DTRManagementTable/columns.tsx, client/src/graphql/queries/timesheetQueries.ts, client/src/utils/types/timeEntryTypes.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-286)
run docker.
or
npm run dev and dotnet watch
HR Admins can now see dynamic data of the position of an employee.
Proof
[screen-capture (1).webm](https://github.com/framgia/sph-hris/assets/109579325/92511b25-bfd2-48e7-bf07-2789cc315a60)
=> HRIS-286 [FE] Add the respective position on each of the employees in the DTR Management page

api/Context/HrisContext.cs, api/DTOs/LeavesTableDTO.cs, api/Entities/Leave.cs, api/Enums/ErrorMessageEnum.cs, api/Enums/InputValidationMessageEnum.cs, api/Enums/RequestStatusEnum.cs, api/Enums/SuccessMessageEnum.cs, api/Interfaces/ISoftDeletable.cs, api/Migrations/20230608020711_AddLeaveIsDeleted.Designer.cs, api/Migrations/20230608020711_AddLeaveIsDeleted.cs, api/Requests/CancelLeaveRequest.cs, api/Schema/Mutations/LeaveMutation.cs, api/Services/LeaveService.cs, api/Utils/Validation/LeaveServiceInputValidation.cs, client/src/components/molecules/LeaveManagementResultTable/columns.tsx, client/src/graphql/mutations/leaveMutation.ts, client/src/graphql/queries/leaveQuery.ts, client/src/hooks/useLeave.ts, client/src/utils/types/leaveTypes.ts
- https://framgiaph.backlog.com/view/HRIS-272
- None
- In the ```api``` directory, run ``` dotnet ef database update ``` & ```dotnet run```
- Cancel action on ``` http://localhost:3000/my-leaves?year=2023 ``` should cancel the leave filed.
- Before cancelling, it should prompt a confirmation window for the cancellation
https://github.com/framgia/sph-hris/assets/109492180/63c2abb5-aa4f-4632-97b0-acc0ee5ade85
=> HRIS-272 [BE/FE] Add functionality to enable users to cancel their leave

client/src/components/molecules/UserMenuDropdown/index.tsx, client/src/components/organisms/Header/index.tsx, client/src/utils/styles/tailwind.css
- https://framgiaph.backlog.com/view/HRIS-298
- Figma Link: https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?type=design&node-id=5361-28454&t=UEVBijTM0IWC9cJk-4
- It should now have an update user dropdown menu based on the request from client
[user dropdown.webm](https://github.com/framgia/sph-hris/assets/108642414/038d3d07-f580-4a58-a587-b9ec3472ec2b)
=> HRIS-298 [FE] Implement a User Dropdown Menu in the User Profile

api/Enums/ErrorMessageEnum.cs, api/Enums/NotificationTypeEnum.cs, api/Enums/SuccessMessageEnum.cs, api/NotificationDataClasses/OvertimeData.cs, api/Requests/CreateSummaryRequest.cs, api/Schema/Mutations/OvertimeMutation.cs, api/Services/NotificationService.cs, api/Services/OvertimeService.cs, api/Subscriptions/SubscriptionObjectType.cs, api/Utils/Validation.cs
- https://framgiaph.backlog.com/view/HRIS-302
- Request task BE
- In the ```api``` directory, run ``` dotnet run ```
- Go to ``` http://localhost:5257/graphql/ ```
- Run this mutation:
```
mutation ($overtimeSummary: CreateSummaryRequestInput!){
createSummarizedOvertime(overtimeSummary: $overtimeSummary){
data
}
}
```
```
{
"overtimeSummary": {
"hrAdminId": 21,
"managerId": 57,
"startDate": "2023-01-17",
"endDate": "2023-01-31"
}
}
```
```
subscription {
overtimeSummaryCreated(id: 57) {
data
}
}
```
- After the request, it should send a notification to the manager (Daisuke)
https://github.com/framgia/sph-hris/assets/109492180/76e24a47-d450-4d6e-a11d-affe34398857
=> HRIS-302 [BE] Implement New Overtime Request for Assistant Manager and Managers

client/src/components/molecules/AddNewBulkOvertimeModal/index.tsx, client/src/pages/my-overtime.tsx, client/src/utils/createLeaveHelpers.ts, client/src/utils/types/formValues.ts, client/src/utils/validation/index.ts
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-303&assignee=405757)
npm run dev and dotnet run
Team Leaders have access to the File Bulk Overtime button which allows them to file a bulk overtime for the members under him/her
Proof
[screen-capture.webm](https://github.com/framgia/sph-hris/assets/109579325/ea562d70-fe4a-4839-b06e-f750422a0d72)
=> HRIS-303 [FE] Create Bulk Overtime Modal for Team Leader

client/src/components/molecules/HROvertimeFilterDropDown/index.tsx, client/src/components/molecules/MyOvertimeTable/ManagerSummaryDropdown.tsx, client/src/pages/overtime-management.tsx
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-304)
npm i and dotnet run
go to http://localhost:3000/overtime-management
HR Admins can filter the overtime management page to the salary period (1-15 or 16-31) 
Send Summary button allows HR Admin to send the salary period to the Manager
Proof:
[screen-capture.webm](https://github.com/framgia/sph-hris/assets/109579325/5c49cb20-b891-45bf-a195-de3ae951030f)
=> HRIS-304 [FE] Create dropdown button for sending summarized overtime request from HR Admin to Manager

api/DTOs/MyOvertimeDTO.cs, api/Enums/ErrorMessageEnum.cs, api/Schema/Mutations/OvertimeMutation.cs, api/Services/OvertimeService.cs, client/src/components/molecules/AddNewBulkOvertimeModal/index.tsx, client/src/graphql/mutations/overtimeMutation.ts, client/src/hooks/useOvertime.ts, client/src/utils/types/overtimeTypes.ts
https://framgiaph.backlog.com/view/HRIS-315
- There should be existing time entries in the requested date for the members to be added in the request
- (docker) run `docker compose up db api client -d`
- go to `My Overtime` page
- Only team leader should be able to send request
- There should be error message if request failed
- There should be success message if request succeeded
- The modal should only close if the request is successful
https://github.com/framgia/sph-hris/assets/111718037/395156ed-0a3e-4aad-aa06-36c25c53d368
=> HRIS-315 [BE/FE] Integrate Bulk Overtime request

client/src/components/molecules/LeaveCellDetailsModal/index.tsx
- https://framgiaph.backlog.com/view/HRIS-321
- Revision task
- It should now automatically reflect the data when trying to open a modal in the cell
[asdf.webm](https://github.com/framgia/sph-hris/assets/108642414/fea512e1-0a46-4149-b2f5-133d3b8b1359)
=> HRIS-321-01 [Bugfix] Fix delayed data fetched in the cell information modal

api/Services/ApprovalService.cs, api/Services/NotificationService.cs, client/src/components/molecules/EditLeaveModal/EditTab.tsx, client/src/components/molecules/EditUndertimeModal/EditTab.tsx
- https://framgiaph.backlog.com/view/HRIS-324
- In the root directory run ``` docker compose up api db client -d ```
- Existing resolved overtime request notification
- In the ```http://localhost:3000/notifications```
- Check the resolved overtime requests detail
- It should reflect the correct value for requested Time In and Time Out
=> HRIS-324 [BE] Fix invalid date data in requestedTimeIn and requestedTimeout in overtime approve/disapprove notification

api/Context/HrisContext.cs, api/Entities/ChangeScheduleRequest.cs, api/Entities/Notification.cs, api/Enums/NotificationTypeEnum.cs, api/Migrations/20230706055350_AddChangeScheduleRequest.Designer.cs, api/Migrations/20230706055350_AddChangeScheduleRequest.cs, api/NotificationDataClasses/ChangeScheduleData.cs, api/NotificationDataClasses/NotificationData.cs, api/Requests/ChangeSchedRequest.cs, api/Schema/Mutations/EmployeeScheduleMutation.cs, api/Services/EmployeeScheduleService.cs, api/Services/NotificationService.cs, api/Subscriptions/SubscriptionObjectType.cs, api/Utils/Validation.cs, api/Utils/Validation/EmployeeScheduleServiceValidation.cs
https://framgiaph.backlog.com/view/HRIS-333
- There is a new migration file
- Don't forget the authorization token when running the mutation and subscriptions
- (docker) run `docker compose up db api --build`
- To listen to subscription/notification, run the following subscription
```
subscription {
notificationCreated(id: <id of recipient>) {
id
type
data
readAt
isRead
}
}
```
- To create change shift request, run the following sample mutation
```
mutation ($request: ChangeSchedRequestInput!) {
changeScheduleRequest(request: $request) {
id
}
}
{
"request": {
"leaderIds":[1,6],
"workingDays": [
{
"day": "monday",
"from": "09:30",
"to": "18:30",
"breakFrom": "12:00",
"breakTo": "13:00"
},
{
"day": "tuesday",
"from": "09:30",
"to": "18:30", …
```
=> HRIS-333 [BE] Implement add new request schedule

api/Dockerfile, client/src/graphql/mutations/overtimeMutation.ts
- https://framgiaph.backlog.com/view/HRIS-358
- There should be existing time entries in the requested date for the members to be added in the request
- (docker) run docker compose up db api client
- go to My Overtime page
- Only team leader should be able to send request
- There should be error message if request failed
- There should be success message if request succeeded
- The modal should only close if the request is successful
https://github.com/framgia/sph-hris/assets/142206621/6ff4e2c9-c710-481e-a344-9552ec8cbd5e
=> [HRIS-358]-[Bugtask] Fixed error when using bulk overtime

api_v2/.eslintrc.js, api_v2/package-lock.json, api_v2/package.json, api_v2/src/app.module.ts, api_v2/src/graphql/graphql.ts, api_v2/src/graphql/schema.gql
https://framgiaph.backlog.com/view/HRIS-368
- This ticket is the groundwork to be able to use graphql 
- None expected pre-conditions apart from running `npm i `and `npm run dev`
- It should follow the list of definition of done
- No screenshots necessary because this is a config/groundwork related ticket.
=> HRIS 368 GraphQL & Schema Setup

api_v2/prisma/schema.prisma, api_v2/src/app.module.ts, api_v2/src/decorators/access-token.decorator.ts, api_v2/src/guards/access-token.guard.ts, api_v2/src/main.ts, api_v2/src/sign-in/sign-in.module.ts, api_v2/src/sign-in/sign-in.resolver.spec.ts, api_v2/src/sign-in/sign-in.resolver.ts, api_v2/src/sign-in/sign-in.service.spec.ts, api_v2/src/sign-in/sign-in.service.ts, client/src/graphql/mutations/signInMutation.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-372)
- No notes for declaring
- Switch the backend url to http://localhost:3000/graphql
- Definition of done items should be working
https://github.com/framgia/sph-hris/assets/169010392/df630729-9e79-4f1d-ae94-76fd35e817fa
=> HRIS 372 Login: Google Sign-In

api_v2/.gitignore, api_v2/package-lock.json, api_v2/package.json, api_v2/src/app.module.ts, api_v2/src/file-upload/file-upload.module.ts, api_v2/src/file-upload/file-upload.service.spec.ts, api_v2/src/file-upload/file-upload.service.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-365)
- This service does not have its own resolver and is expected to be used by other services for their file uploading needs.
- Supply the collection proper collection name proper foldering
- **IMPORTANT**: The header value`Apollo-Require-Preflight: true` must be set in order for the file uploading to proceed as expected, otherwise you will be returned with a 400 Bad Request error
- None
- Items listed under the definition of done must be working
https://github.com/framgia/sph-hris/assets/169010392/9a540cd6-6a29-4640-9c3d-cfafcc33cc39
=> HRIS 365 Migrate File Uploader Util

api_v2/src/app.module.ts, api_v2/src/graphql/graphql.ts, api_v2/src/logout/logout.module.ts, api_v2/src/logout/logout.resolver.spec.ts, api_v2/src/logout/logout.resolver.ts, api_v2/src/logout/logout.service.spec.ts, api_v2/src/logout/logout.service.ts
Backlog [Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-373&milestone=314112)
- None
- Existing user token in Personal_Access_Tokens table
- Run npm start 
- Change the Backend URL http://localhost:3001/graphql
- It should be the same output with the ASP.net
NestJS GraphQL output:
Error when the Token does not exist in the Personal_Access_Tokens table:
ASP.net GraphQL output:
Error when the Token does not exist in the Personal_Access_Tokens table:
=> [HRIS-373] [BE] Migrate Logout

api_v2/src/utilities/validation.util.ts, api_v2/src/utilities/validation/approvalServiceInputValidation.ts, api_v2/src/utilities/validation/emploteeScheduleServiceValidation.ts, api_v2/src/utilities/validation/employeeServiceInputValidation.ts, api_v2/src/utilities/validation/leaveServiceInputValidation.ts, api_v2/src/utilities/validation/overtimeServiceInputValidation.ts, api_v2/src/utilities/validation/timeInServiceInputValidation.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-364)
wasn't able to create a test since jest need a service in order to run the validations testing
Will get back to this once all service are migrated
=> HRIS-364 Migrate Validations Util

api_v2/src/work-interruption/work-interruption.service.ts
Hotfix/HRIS-375 Navbar: Break Time / Work Interruption
Backlog Link: https://framgiaph.backlog.com/view/HRIS-375
to run 
mutation ($interruption: CreateInterruptionRequestInput!) {
createWorkInterruption(interruption: $interruption) {
id
}
}
=> hotfix/HRIS-375 Navbar: Break Time / Work Interruption

api_v2/.eslintrc.js, api_v2/.prettierrc, api_v2/config/bull.config.ts, api_v2/config/cache.config.ts, api_v2/config/hris-api.config.ts, api_v2/config/jwt.config.ts, api_v2/config/queue.config.ts, api_v2/config/slack.config.ts, api_v2/src/app.module.ts, api_v2/src/graphql/graphql.ts, api_v2/src/graphql/schema.gql, api_v2/src/user/user.module.ts, api_v2/src/user/user.resolver.spec.ts, api_v2/src/user/user.resolver.ts, api_v2/src/user/user.service.spec.ts, api_v2/src/user/user.service.ts, api_v2/tsconfig.json
https://framgiaph.backlog.com/view/HRIS-378
- No specific note entry
Commands to run:
NestJS query for User ID
NestJS query for All Users
=> HRIS-378 Navbar: API migration Fetch User Name and Role
