framgia/sph-hris

- api/Program.cs
- api/Requests/TimeOutRequest.cs
- api/Schema/Mutations/TimeOutMutation.cs
- api/Services/TimeOutService.cs
https://framgiaph.backlog.com/view/HRIS-18
- Please note that I have restructured the schema folder which is also reflected my previous pr hris-16
- You can access the graphql playground enpoint at http://localhost:5257/graphql/
- run docker compose 
- http://localhost:5257/graphql/
- try running this mutation
```
mutation{
updateTimeEntry(timeOut: {
userId: 1
timeEntryId: 1
timeHour: "PT18H50M"
remarks: "Goodbye [logout]"
})
}
```
You should receive the response below upon running the mutation
```
{
"data": {
"updateTimeEntry": "Successful Time Out!"
}
}
```
> HRIS-18 [BE] Create time out functionality

- client/package-lock.json
- client/package.json
- client/src/components/organisms/Header/index.tsx
- client/src/components/organisms/TimeInDrawer/index.tsx
- client/src/components/organisms/TimeOutDrawer/index.tsx
- client/src/components/templates/DrawerTemplate/index.tsx
- client/src/components/templates/Layout/index.tsx
https://framgiaph.backlog.com/view/HRIS-28
Optional
- I added all the possible fields on this one. It will be put into hidden during integration.
- All fields are optional. Not required.
- Moved the file input to its traditional location which is below the form input.
cd client
npm i
npm run dev
click on the time in button
Users can pull the time in drawer by clicking on the time in button
Users can close the timein drawer by clicking the close button, close mark on top, and also clicking outside the drawer
> HRIS-28 [Markup] Create Drawer Markup

- api/Program.cs
- api/Requests/LogoutRequest.cs
- api/Schema/Mutations/LogoutMutation.cs
- api/Services/LogoutService.cs
- client/.gitignore
- client/src/components/molecules/UserMenuDropdown/index.tsx
- client/src/graphql/mutations/logOutMutation.ts
- client/src/hooks/useLogOutMutation.ts
- client/src/pages/index.tsx
- client/src/pages/sign-in.tsx
- client/src/utils/ssr.ts
https://framgiaph.backlog.com/view/HRIS-14
- None
- Existing user token in Personal_Access_Tokens table
- User can logout their session
- The tokens stored in the backend will be removed upon logout
- After logout, the user will then be redirected to the login page
> HRIS-14 [FE] Integration logout functionality

- api/Schema/Queries/TimeSheetQuery.cs
- api/Services/TimeSheetService.cs
- https://framgiaph.backlog.com/view/HRIS-21
- None
- Access the query in the graphQL playground
```
query {
timeEntriesByEmployeeId (id: 1) {
id
timeIn {
timeHour
}
timeOut {
timeHour
}
}
}
```
- If the status code is 200 and it returns a list of time entries for that employee then the request is successful
```
{
"data": {
"timeEntriesByEmployeeId": [
{
"id": 1,
"timeIn": {
"timeHour": "PT9H15M"
},
"timeOut": {
"timeHour": "PT18H15M"
}
},
{
"id": 3,
"timeIn": {
"timeHour": "PT10H15M"
},
"timeOut": {
"timeHour": "PT19H59M"
}
}
]
}
}
```
> HRIS-21 [BE] Create get timesheet functionality

- client/src/components/molecules/FooterTable/index.tsx
- client/src/components/molecules/NotificationPopOver/index.tsx
- client/src/components/molecules/TimeSheetFilterDropdown/index.tsx
- client/src/components/molecules/UserMenuDropdown/index.tsx
- client/src/pages/dtr-management.tsx
- client/src/utils/mapping/dtrManagementMap.tsx
https://framgiaph.backlog.com/view/HRIS-29
N/A
- docker compose build (to build the images)
- docker compose up (to run the containers)
- docker compose up --build (to build and run the containers)
- docker compose down (to stop the containers)
It should now fixed the Deformation of Timesheet Dropdown
[1.webm](https://user-images.githubusercontent.com/108642414/212615843-c758bd5d-14db-4512-978a-0851cb420f5a.webm)
> HRIS-29 [BugTask] DTR Management Deformation

- api/Context/HrisContext.cs
- api/Entities/TimeEntry.cs
- api/Entities/WorkInterruption.cs
- api/Entities/WorkInterruptionType.cs
- api/Enums/WorkInterruptionEnum.cs
- api/Migrations/20230117091858_AddWorkInterruption.Designer.cs
- api/Migrations/20230117091858_AddWorkInterruption.cs
- api/Program.cs
- api/Requests/CreateInterruptionRequest.cs
- api/Schema/Mutations/InterruptionMutation.cs
- api/Seeders/DatabaseSeeder.cs
- api/Services/InterruptionService.cs
https://framgiaph.backlog.com/view/HRIS-51
- You can access the graphql playground enpoint at http://localhost:5257/graphql/
- To run the mutation, use the following below:
```
mutation($interruption:CreateInterruptionRequestInput!)
{
createWorkInterruption(interruption:$interruption){
id
timeOut
remarks
}
}
```
- And use this as your variables:
```
{
"interruption":{
"timeEntryId": 3,
"workInterruptionTypeId": 5,
"timeOut": "PT13H00M",
"timeIn": "PT13H30M",
"remarks": "sample remarks",
"otherReason": "sample other reason"
}
}
```
- Also, please bear in mind the ID you pass on your variables such as the time entry and work interruption ids
- run the db service on docker first using docker desktop or `docker-compose up -d db`
- cd api
- `dotnet ef …
> HRIS-51 [BE] Implement file work interruption request functionality

- api/Schema/Queries/TimeSheetQuery.cs
- api/Services/TimeSheetService.cs
https://framgiaph.backlog.com/view/HRIS-40
- Existing Time In/Time Out record inside the Times table
- in your terminal run ``` docker compose up --build ```
- access ``` http://localhost:5257/graphql/ ```
- Try this query:
```
query ($id: Int!) {
timeById(id: $id) {
timeHour
remarks
}
}
```
- Variable is the Id of the Time query we want to get:
```
{
"id": 1
}
```
- It should return the TimeHour and Remark of the Entry
```
{
"data": {
"timeById": {
"timeHour": "PT9H15M",
"remarks": "First time in"
}
}
}
```
> HRIS-40 [BE] Implement GET specific Time Entry functionality

- client/package-lock.json
- client/package.json
- client/src/components/organisms/Header/index.tsx
- client/src/components/organisms/WorkInterruptionDrawer/index.tsx
- client/src/components/templates/Layout/index.tsx
- client/src/utils/styles/tailwind.css
- client/src/utils/types/formValues.ts
- client/src/utils/validation/index.ts
https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-50&assignee=405757
Clock and dropdown might look different from figma but this is the full extent of the customizability of tailwind. 
It should display confirm work interruption drawer upon click of orange button.
> HRIS-50 [Markup] Create Work Interruption Drawer Markup

- api/DTOs/WorkInterruptionDTO.cs
- api/Program.cs
- api/Requests/ShowInterruptionRequest.cs
- api/Schema/Mutations/InterruptionMutation.cs
- api/Schema/Queries/InterruptionQuery.cs
- api/Services/InterruptionService.cs
- client/next.config.js
- client/src/middleware.ts
- client/src/pages/api/auth/[...nextauth].ts
https://framgiaph.backlog.com/view/HRIS-56
- You can access the graphql playground enpoint at http://localhost:5257/graphql/
- To run the query, use the following below:
```
query ($interruption:ShowInterruptionRequestInput!){
interruptionsByTimeEntryId(interruption:$interruption){
id
timeOut
timeIn
otherReason
workInterruptionType{
id
name
}
}
}
```
- And use this as your variables:
```
{
"interruption": {
"timeEntryId": 3
}
}
```
- run the db service on docker first using docker desktop or `docker-compose up -d db`
- cd api
- `docker compose up`
- You should receive the response below upon running the mutation:
```
{
"data": {
"interruptionsByTimeEntryId": [
{
"id": 1,
"timeOut": "11:00:00",
"timeIn": "11:30:00",
"otherReason": null, …
```
> HRIS-56 [BE] Implement GET list of work interruptions for a specific employee functionality

- api/DTOs/TimeEntryDTO.cs
- api/Requests/TimesheetRequest.cs
- api/Schema/Queries/TimeSheetQuery.cs
- api/Services/TimeSheetService.cs
https://framgiaph.backlog.com/view/HRIS-48
- Filtering is currently done after database query, which is inefficient.
- Filtering according to status and day will be done in the FE
- try this query
```
query Filter($filter: TimeEntryFilterInput!){
timeEntries(
filter: $filter
) {
id
date
}
}
```
- with variables `startDate` and `endDate` which you can manually change:
```
{
"filter": {
"startDate": "2023-02-01",
"endDate": "2023-02-15"
}
}
```
- The query should return time entries in between `startDate` and `endDate`, inclusive
> HRIS-48 [BE] Implement GET data based on the filter options

- api/DTOs/TimeDTO.cs
- client/src/components/molecules/DTRManagementTable/columns.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
- client/src/components/organisms/TimeInDrawer/index.tsx
- client/src/components/organisms/TimeOutDrawer/index.tsx
- client/src/components/templates/DrawerTemplate/index.tsx
- client/src/graphql/queries/timesheetQueries.ts
- client/src/hooks/useTimesheetQuery.ts
- client/src/utils/types/timeEntryTypes.ts
https://framgiaph.backlog.com/view/HRIS-41
- FE Integration
- Go to the root directory and run ``` docker compose up --build ```
- Pre existing Time Entries
- If you click a specific Time In time with a dot, it will show a drawer with its remark
- If you click a specific Time In time with a dot, it will show a drawer with its remark
DTR Management Page
My DTR
> HRIS-41 [FE] Integrate GET specific Time Entry functionality

- client/src/components/atoms/Alert/index.tsx
- client/src/components/organisms/TimeInDrawer/index.tsx
- client/src/components/organisms/TimeOutDrawer/index.tsx
- client/src/components/organisms/ViewDetailsDrawer/index.tsx
- client/src/components/templates/Layout/index.tsx
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-42)
cd client
npm run dev
> HRIS-42 [Markup] Create Drawer which displays the list of downloaded files and remarks of the time entry

- api/Requests/TimesheetRequest.cs
- api/Schema/Queries/TimeSheetQuery.cs
- api/Services/TimeSheetService.cs
- client/src/components/molecules/DTRManagementTable/index.tsx
- client/src/components/molecules/TimeSheetFilterDropdown/index.tsx
- client/src/graphql/queries/timesheetQueries.ts
- client/src/hooks/useTimesheetQuery.ts
- client/src/pages/dtr-management.tsx
https://framgiaph.backlog.com/view/HRIS-49
- There were changes in the filtering. Previously, 15-days filter is included but is now removed
- go to `http://localhost:3000/dtr-management`
- At first load, it should show all time entries of the current date
- Clicking "Update Results" in Timesheet Filters, it will make a query to the backend according to the selected filters
- New Timesheet Filters UI
- Filtering
https://user-images.githubusercontent.com/111718037/213950634-1b439494-d335-4e9d-94f7-ac4645e92dca.mp4
> HRIS-49 [FE] Integrate GET data based on the filter options

- api/Requests/UpdateInterruptionRequest.cs
- api/Schema/Mutations/InterruptionMutation.cs
- api/Services/InterruptionService.cs
https://framgiaph.backlog.com/view/HRIS-53
- Please create a time entry first if not yet created and use its Id on the variables
- You can access the graphql playground enpoint at http://localhost:5257/graphql/
- To run the update and delete mutation, use the following below:
```
mutation($interruption: UpdateInterruptionRequestInput!){
updateWorkInterruption(interruption:$interruption)
}
mutation($id:Int!){
deleteWorkInterruption(id:$id)
}
```
- And use this as your variables respectively:
```
{
"interruption": {
"id": 24,
"otherReason":"Update NEW REASON",
"remarks":"Update remarks",
"timeIn":"13:51:00",
"timeOut":"13:01:00",
"workInterruptionTypeId": 5
}
}
{
"id":24
}
```
- Create a time entry first if not yet created
- …
> HRIS-53 [BE] Implement Edit and Delete Work Interruption Request functionality

- api/DTOs/TimeEntriesSummaryDTO.cs
- api/DTOs/TimeEntryDTO.cs
- api/Schema/Queries/TimeSheetQuery.cs
- api/Services/TimeSheetService.cs
https://framgiaph.backlog.com/view/HRIS-46
- Added computation for undertime when there's work interruption, it affects the whole DTRManagement table
- `docker compose up --build` or `dotnet run` on `api` directory
- use this query and adjust according to need
```
query Summary($startDate: String, $endDate:String){
timesheetSummary(
startDate: $startDate
endDate: $endDate
) {
user{
name
}
leave
absences
late
undertime
overtime
}
}
```
- Use and/or adjust these query variables
```
{
"startDate": "2023-01-01",
"endDate": "2023-01-30"
}
```
- The query should return the timesheet summary of all employees between `startDate` and `endDate` inclusively.
- The result should show the number of `absences`, number of `leaves`, minutes of …
> HRIS-46 [BE] Implement GET summary data functionality

- client/src/components/molecules/DTRSummaryTable/DesktopTable.tsx
- client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
- client/src/components/molecules/DTRSummaryTable/columns.tsx
- client/src/components/molecules/DTRSummaryTable/index.tsx
- client/src/components/molecules/SummaryMenuDropdown/index.tsx
- client/src/pages/dtr-management.tsx
- client/src/utils/constants/index.ts
- client/src/utils/interfaces/index.tsx
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-45)
cd client
npm run dev
or 
run docker
http://localhost:3000/dtr-management
It should allow the users to change from DTR management table to DTR Summary table and vice versa. 
Title: DTR Summary Table
Title: Mobile DTR Summary Table with button to switch back to DTR management table
> HRIS-45 [Markup] Create DTR Table Summary Markup

- client/src/components/organisms/TimeInDrawer/index.tsx
- client/src/components/organisms/TimeOutDrawer/index.tsx
- client/src/components/organisms/ViewDetailsDrawer/index.tsx
- client/src/components/templates/DrawerTemplate/index.tsx
- client/src/graphql/queries/timesheetQueries.ts
- client/src/utils/types/timeEntryTypes.ts
https://framgiaph.backlog.com/view/HRIS-44
- There's a fix on the timeEntryDTO file on sir Arden's next pr 🙇 
- Open a cmd terminal > go to the root directory and run the command ``` docker compose up --build ```
- Go to ``` http://localhost:3000/my-daily-time-record ``` & ``` http://localhost:3000/dtr-management ``` 
- The time itself on the login and logout should be clickable and displays  the details of the login or logout
My DTR page:
DTR Management page:
Checking:
> HRIS-44 [FE] Integrate GET remarks and uploaded files on the time entry

- api/DTOs/TimeEntryDTO.cs
- api/DTOs/WorkInterruptionDTO.cs
- client/package-lock.json
- client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
- client/src/components/molecules/DTRManagementTable/columns.tsx
- client/src/components/molecules/InterruptionTimeEntriesModal/Table.tsx
- client/src/components/molecules/InterruptionTimeEntriesModal/columns.tsx
- client/src/components/molecules/InterruptionTimeEntriesModal/index.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
- client/src/components/templates/ModalTemplate/index.tsx
- client/src/graphql/queries/workInterruptionQuery.ts
- client/src/hooks/useInterruptionType.ts
- client/src/utils/constants/interruptionDummyTimeEntries.ts
- client/src/utils/interfaces/index.tsx
- client/src/utils/types/workInterruptionTypes.ts
https://framgiaph.backlog.com/view/HRIS-57
https://framgiaph.backlog.com/view/HRIS-59
- I have already combined 2 tasks for this PR since the modal component is already reusable for each My DTR and DTR Management Pages and would be difficult to check if I separate these into different PRs.
- Login
- Go to My DTR page
- Click the Clock Icon (Time Entry Icon) 
- Go to DTR Management page
- Click the Clock Icon (Time Entry Icon) 
- It should be able to display the work interuption entries on the modal based on the user's time entry
My DTR Page
https://user-images.githubusercontent.com/110364637/214267827-d0ae5947-f999-4308-aee0-c9dc268e3d6c.mp4
DTR Manangement Page
https://user-images.githubusercontent.com/110364637/214267900-237cbfdd-fbdf-4c92-adc9-12e689fe5530.mp4
> HRIS-57 [FE] Integrate GET list of work interruptions for a specific employee functionality

- client/src/components/molecules/DTRSummaryTable/DesktopTable.tsx
- client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
- client/src/components/molecules/DTRSummaryTable/columns.tsx
- client/src/components/molecules/DTRSummaryTable/index.tsx
- client/src/components/molecules/TimeSheetFilterDropdown/index.tsx
- client/src/graphql/queries/timesheetQueries.ts
- client/src/hooks/useTimesheetQuery.ts
- client/src/pages/dtr-management.tsx
- client/src/utils/types/timeEntryTypes.ts
https://framgiaph.backlog.com/view/HRIS-47
- all the displayed data are defaulted to in relation to current date
- or `npm run dev` on `client` directory and `dotnet watch` on `api` directory
- go to `http://localhost:3000/dtr-management`
- open summary table by clicking `Summary` button on the right of `Filter` button
- DTRManagement page should display summary of all employees (default data related to current date)
- User can filter to other date range using the `filter` button
[SummaryIntegration.webm](https://user-images.githubusercontent.com/111718037/214269806-605d141c-91b9-45c1-a7e0-bb63ac836035.webm)
> HRIS-47 [FE] Integrate GET summary data functionality

- client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
- client/src/utils/constants/index.ts
- client/src/utils/interfaces/index.tsx
https://framgiaph.backlog.com/view/HRIS-47
- go to DTRManagement page and set it to mobile view
- Mobile view of Summary Table should now properly display employees name
> HRIS-47-01 [FE] Fix Mobile view of Summary Table

- client/src/components/organisms/ViewDetailsDrawer/index.tsx
https://framgiaph.backlog.com/view/HRIS-44
- Fix only
- Add ``` NEXT_PUBLIC_MEDIA_URL=http://localhost:5257/media/ ``` in your client .env variables
- go to DTRManagement or MyDTR page and view the details of the login
- Longer filenames will be truncated
- Download button will download the file directly
https://user-images.githubusercontent.com/109492180/214483871-bb21230c-9038-4972-8e4e-8140395f8113.mp4
> HRIS-44-01 [FE] Fix download button and truncate long filenames

- api/Context/HrisContext.cs
- api/DTOs/UserDTO.cs
- api/Entities/Role.cs
- api/Entities/User.cs
- api/Enums/RoleEnum.cs
- api/Migrations/20230125101948_AddRoles.Designer.cs
- api/Migrations/20230125101948_AddRoles.cs
- api/Migrations/20230126020829_UpdateRolesSeeder.Designer.cs
- api/Migrations/20230126020829_UpdateRolesSeeder.cs
- api/Seeders/DatabaseSeeder.cs
- api/Services/InterruptionService.cs
- api/Services/TimeInService.cs
- client/src/components/molecules/InterruptionTimeEntriesModal/UpdateInterruptionTimeEntriesModal.tsx
- client/src/components/molecules/InterruptionTimeEntriesModal/columns.tsx
- client/src/graphql/mutations/workInterruptionMutation.ts
- client/src/graphql/queries/UserQuery.ts
- client/src/graphql/queries/workInterruptionQuery.ts
- client/src/hooks/useInterruptionType.ts
- client/src/utils/constants/interruptionDummyTimeEntries.ts
- client/src/utils/constants/roles.ts
- client/src/utils/interfaces/index.tsx
- client/src/utils/types/userTypes.ts
https://framgiaph.backlog.com/view/HRIS-54
- Please run the migrations using `dotnet ef database update`
- You can play around the user by changing roles to determine restrictions
- `cd api`
- `dotnet ef database update`
- go to `http://localhost:3000/my-daily-time-record` and `http://localhost:3000/dtr-management`
- and click on the time entries button
- update or delete some entries
- User should be able to Edit and Delete Work Interruptions based on roles and should be able to edit or delete one with 1 day leniency
- Other Roles (not an HR Admin)
https://user-images.githubusercontent.com/110364637/214570673-26636fa3-0366-49d7-816f-c7dcd0bd17e2.mp4
- HR Admin
https://user-images.githubusercontent.com/110364637/214570761-e5fc8ef6-7d74-4f7d-aea7-e0b6ad20d3e7.m …
> HRIS-54 [FE] Integrate Edit and Delete Work Interruption Request functionality

- client/src/components/molecules/UserMenuDropdown/index.tsx
- client/src/pages/sign-in.tsx
https://framgiaph.backlog.com/view/HRIS-61
- Bug fix only
- Run ``` docker compose up --build ```
- The callback URL for logout should be ``` /sign-in ```
https://user-images.githubusercontent.com/109492180/214801988-ceb319c5-3769-4d15-a3de-50588e98de94.mp4
> HRIS-61 [Bugtask] Url is wrong when logout

- client/src/components/molecules/TimeSheetFilterDropdown/index.tsx
- client/src/hooks/useTimesheetQuery.ts
- client/src/pages/dtr-management.tsx
https://framgiaph.backlog.com/view/HRIS-62
- go to DTR Management page
- After reloading the page, the tables should still display the same result on the same table from the same filter.
[Filter Persist.webm](https://user-images.githubusercontent.com/111718037/215006963-f7583cce-01e5-4c53-8b0c-aaf4a0e34db8.webm)
> HRIS-62 [BugTask] Filter should not reset when refresh

- client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
https://framgiaph.backlog.com/view/HRIS-64
- go to MyDTR page and DTR Management page
- Correct dot icon should be beside `Time In` and `Time Out` on both pages
- `Time In` and `Time Out` with `remarks` is now clickable and will open the remarks drawer
[DotMobileView.webm](https://user-images.githubusercontent.com/111718037/215399258-51fb5412-ce40-47c9-9760-ac8af862fe40.webm)
> HRIS-64 [BugTask] Integrate dot remarks in mobile view

- client/src/pages/dtr-management.tsx
- client/src/pages/my-daily-time-record.tsx
https://framgiaph.backlog.com/view/HRIS-62
- go to MyDTR page and DTR Management page
- Search keyword should remain the same on every page reload
[searchKey.webm](https://user-images.githubusercontent.com/111718037/215380625-bb5c2428-d065-4ebc-a9e2-6dcb28fd8721.webm)
> HRIS-62-01 [BugTask] Search keyword persists on page reload

- api/Program.cs
- api/Requests/TimeEntryRequest.cs
- api/Schema/Mutations/TimeEntryMutation.cs
- api/Services/TimeSheetService.cs
https://framgiaph.backlog.com/view/HRIS-82
- `docker compose up --build` or `dotnet run` in `api` directory
- use this mutation
```
mutation ($updatedTimeEntry: UpdateTimeEntryInput!){
updateOneTimeEntry(updatedTimeEntry: $updatedTimeEntry)
}
```
- and edit these variables (userId is the id of user doing the editing)
```
{
"updatedTimeEntry": {
"userId": 3,
"timeEntryId" : 1004,
"timeIn": "11:16:59",
"timeOut": "17:59:59"
} 
}
```
- HR Admin can edit `Time In` and `Time Out` of a `Time Entry`
- Only HR Admin should be able to edit/update
- It should create new `Time` entity if the selected `TimeEntry` has no `TimeInId` or `TimeOutId`, otherwise, just update the existing entity for `TimeIn` and `TimeOut`
[edit …
> HRIS-82 [BE] Implement Edit time entry functionality

- api/Context/HrisContext.cs
- api/Migrations/20230201065141_LeaveSeeder.Designer.cs
- api/Migrations/20230201065141_LeaveSeeder.cs
- api/Migrations/20230201072040_UndertimeSeeder.Designer.cs
- api/Migrations/20230201072040_UndertimeSeeder.cs
- api/Program.cs
- api/Schema/Queries/LeaveQuery.cs
- api/Seeders/DatabaseSeeder.cs
- api/Services/LeaveService.cs
https://framgiaph.backlog.com/view/HRIS-92
- From the root directory, go to api directory
- run ``` dotnet ef database update ```
- If the seeder does not work, you can run ``` dotnet ef database update 0 ``` to reset the migrations before running ``` dotnet ef database update ```
- In the root directory, run ``` docker compose up --build ```
- Access ``` http://localhost:5257/graphql/ ```
- Run this sample query
``` query {
allLeaves {
id
userId
projectId
leaveTypeId
managerId
otherProject
reason
leaveDate
isWithPay
isLeaderApproved
isManagerApproved
createdAt
updatedAt
}
}
```
- It should return all requested employee leaves
> HRIS-92 [BE] Implement fetch all requested leaves functionality

- api/Services/TimeSheetService.cs
- client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
- client/src/components/molecules/DTRManagementTable/columns.tsx
- client/src/components/molecules/EditTimeEntryModal/index.tsx
- client/src/graphql/mutations/timeEntryMutation.ts
- client/src/hooks/useTimeEntryMutation.ts
https://framgiaph.backlog.com/view/HRIS-83
- Modified returned data from BE
- go to DTR Management page
- Only HR Admin user should be able to edit
- Toast message will display on success or error
- New data will be reflected immediately on table after successful edit
- Both `Time In` and `Time Out` field are optional
- Same behaviors should also be in the mobile view
- Desktop Mode
[EditTimeEntry-FE.webm](https://user-images.githubusercontent.com/111718037/216016445-c25272b6-14a6-41fa-8dc0-ca10b0841a7a.webm)
- Mobile Mode
[EditTimeEntry-Mobile.webm](https://user-images.githubusercontent.com/111718037/216208608-df63b346-4084-4c8b-b32d-ad4f1e7d09e1.webm)
> HRIS-83 [FE] Integrate Edit time entry functionality

- api/DTOs/HeatMapDTO.cs
- api/DTOs/LeaveBreakdownDTO.cs
- api/DTOs/LeaveHeatMapDTO.cs
- api/DTOs/LeavesDTO.cs
- api/DTOs/LeavesTableDTO.cs
- api/Enums/LeaveTypeEnum.cs
- api/Schema/Queries/LeaveQuery.cs
- api/Services/LeaveService.cs
https://framgiaph.backlog.com/view/HRIS-84
- You can refer to the query below and its variables:
```
query($userId:Int!,$year:Int!){
leaves(userId:$userId, year: $year){
heatmap{
january{
value
day
}
}
table{
date
leaveTypeId
}
breakdown{
undertime
sickLeave
withoutPayTotal
withPayTotal
}
}
}
```
```
{
"userId": 1,
"year": 2023
}
```
- `docker compose --build`
- go to http://localhost:5257/graphql/
It should be able to fetch the heatmap data, leaves table and leaves breakdown based on userid and year
> HRIS-84 [BE] Implement Fetch Leave Data for the in My Leaves Page functionality

- client/src/components/molecules/EditTimeEntryModal/index.tsx
https://framgiaph.backlog.com/view/HRIS-83
- Revision 1 from task HRIS-83
- go to DTR Management page
- Any time fields are disabled if there are no initial data
- Save button is disabled if both time fields are empty
- One time field is empty
- Both time field is empty, Save button disabled
> HRIS-83-01 [FE] Fix: Disabled time fields if there are no initial data

- api/DTOs/HeatMapDTO.cs
- api/DTOs/LeaveHeatMapDTO.cs
- api/DTOs/LeavesDTO.cs
- api/Schema/Queries/LeaveQuery.cs
- api/Services/LeaveService.cs
https://framgiaph.backlog.com/view/HRIS-90
- `docker compose up --build` or `dotnet run` on `api` directory
- you can play around using this query
```
query($year:Int!){
yearlyAllLeaves(year: $year){
heatmap{
january{
value
day
}
february{
value
day
}
}
table{
date
leaveTypeId
isWithPay
reason
numLeaves
}
breakdown{
undertime
sickLeave
vacationLeave
emergencyLeave
bereavementLeave
maternityLeave
withoutPayTotal
withPayTotal
}
}
}
```
- using this variable
```
{
"year": 2022
}
```
- The query should return 
- In case of same number of majority type of leave, the type that has earliest/oldest entry will be selected
[FetchYearlySummary.webm](https://user-images.githubusercontent.com/111718037/216528339-4e4ab13c-415b-4da6-8d5c-2cd60ed8a32c.webm)
> HRIS-90 [BE] Implement Fetch Yearly Summary data of all employees functionality

- client/src/components/templates/LeaveManagementLayout/index.tsx
https://framgiaph.backlog.com/view/HRIS-78
- This is revision from branch #52 
npm run dev
- Fixed the mobile scrollable-x tab header
- Added tooltip in Chip remaining paid leave number
[Sun_ HRIS - List of leave.webm](https://user-images.githubusercontent.com/108642414/216823851-ca0cae5e-9f46-4179-8592-1ba0b2bfadd3.webm)
> HRIS-78-01 [Markup] Create List of Leaves tabbed page in Leave Management

- client/src/components/molecules/SummaryFilterDropdown/index.tsx
- client/src/graphql/queries/leaveQuery.ts
- client/src/hooks/useLeave.ts
- client/src/pages/leave-management/yearly-summary.tsx
- client/src/utils/generateData.ts
- client/src/utils/types/leaveTypes.ts
https://framgiaph.backlog.com/view/HRIS-91
https://framgiaph.backlog.com/view/HRIS-95
- This task also covered the task HRIS-95
- go to `http://localhost:3000/leave-management/yearly-summary`
- At first page visit, it should display the data from current year and the URL must have no query
- After selecting a year and clicking `Update Result` in the filter dropdown, the year should reflect on the URL with query key `year`
[YearlySummaryIntegrate.webm](https://user-images.githubusercontent.com/111718037/216879330-90f41259-4056-48a1-a4b7-712cb78f46cd.webm)
> HRIS-91 [FE] Integrate Fetch Yearly Summary data of all employees functionality

- client/src/pages/leave-management/list-of-leave.tsx
- This is a revision from branch https://github.com/framgia/sph-hris/pull/69
- Values on Total Undertime and Leaves should now disregard ending zeros and at max 3 decimal places.
> HRIS-93-01 [FE] Fix: Set the decimal places on Total Undertime and Leaves to 3

- api/Schema/Queries/UserQuery.cs
- client/src/components/molecules/SummaryFilterDropdown/index.tsx
- client/src/components/templates/FilterDropdownTemplate/index.tsx
- client/src/hooks/useLeave.ts
- client/src/hooks/useUserQuery.ts
- client/src/pages/leave-management/leave-summary.tsx
- client/src/pages/leave-management/yearly-summary.tsx
- client/src/pages/my-leaves.tsx
- client/src/utils/maps/filterOptions.ts
- client/src/utils/types/userTypes.ts
https://framgiaph.backlog.com/view/HRIS-89
https://framgiaph.backlog.com/view/HRIS-101
- Filter task, HRIS-101, is also included in this PR
- Filter dropdown from `Yearly Summary` tab/page was also changed to use react-select
- go to `http://localhost:3000/leave-management/leave-summary`
- At first visit of page, there should be no queries in the URL
- Selecting filters then clicking the `Update Results` button would also update the URL, adding the selected filters
- User can type text on dropdown fields to narrow the options
- After reloading the page, the filter values and displayed data should remain the same
- Desktop Mode
[LeaveSummaryDesktop.webm](https://user-images.githubusercontent.com/111718037/217155613-9bb977e8-acb2-41a3-9e5d-3525a9 …
> HRIS-89 [FE] Implement and Integrate Fetch Leave Summary data of a specific employee functionality

- client/src/components/templates/LeaveManagementLayout/index.tsx
- client/src/graphql/queries/leaveQueries.ts
- client/src/hooks/useLeaveQuery.ts
- client/src/pages/my-leaves.tsx
https://framgiaph.backlog.com/view/HRIS-97
- N/A
- Run ``` docker compose up --build ```
- It should reflect the remaining paid leaves on My Leaves and Leave Summary Page
https://user-images.githubusercontent.com/109492180/217202933-37775db1-e6d5-415c-9167-fdc324df148a.mp4
> HRIS-97 [FE] Integrate Remaining Paid Leaves functionality

- api/DTOs/LeavesDTO.cs
- api/Services/LeaveService.cs
- client/src/components/templates/LeaveManagementLayout/index.tsx
- client/src/graphql/queries/leaveQuery.ts
- client/src/utils/types/leaveTypes.ts
- https://framgiaph.backlog.com/view/HRIS-108
N/A
- cd client && npm run dev
- goto `/leave-management/leave-summary` 
- Click the filter and try to Update the result
- Able to update the remaining paid leaves based on the name userId and year provided
[bugtask remaining pad leaves.webm](https://user-images.githubusercontent.com/108642414/217730983-4bb4fa46-a0a5-48ab-86a1-ed8db5adae3b.webm)
> HRIS-108 [BugTask] Remaining Paid Leave should change base on the filter

- client/src/components/templates/Layout/index.tsx
- client/src/components/templates/LeaveManagementLayout/index.tsx
- https://framgiaph.backlog.com/view/HRIS-108
This is the revision of bugtask #83
- Goto the  `/leave-management/leave-summary` page
- The remaining Paid Leaves is now formatted into 3 decimal places
- Also fixed the bug in initial load of page in the drawers
[formatted.webm](https://user-images.githubusercontent.com/108642414/217775287-e53e2b35-ff5c-4245-b5e6-6b003c8039b8.webm)
> HRIS-108-01 [BugTask] Apply Three Decimal Place

- client/src/components/molecules/DTRManagementTable/columns.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
https://framgiaph.backlog.com/view/HRIS-110
- Bugfix on My DTR and DTR Management Time in column
- In the root folder run ``` docker compose up --build ```
- TimeIn time with dot can now be open if there's a file attached or a remark available. If both are none, it will not be clickable 
- 
https://user-images.githubusercontent.com/109492180/218409390-daefdf07-f35c-4416-b05d-ea2cd9f5c9f3.mp4
> HRIS-110 [BugTask] User should able to click Time in or out column in the My DTR and DTR Management

- client/src/components/molecules/AddNewOvertimeModal/index.tsx
- client/src/components/molecules/MyOvertimeTable/columns.tsx
- client/src/pages/my-overtime.tsx
- client/src/utils/types/formValues.ts
- client/src/utils/validation/index.ts
https://framgiaph.backlog.com/view/HRIS-104
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=2741%3A20513&t=G2Cl95iUvU9UB5y0-4
cd api && dotnet run watch
- It should now have a markup for File Overtime Modal
- Applied animation and validation rules with loading submit indicator
[file overtime modal.webm](https://user-images.githubusercontent.com/108642414/218619020-10fa2a14-2e29-465f-8b9d-5bf573da8c23.webm)
> HRIS-104 [Markup] Create File for Overtime Modal

- client/src/components/molecules/BreakdownOfLeavesCard/index.tsx
- client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
- client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
- client/src/components/molecules/LeaveManagementResultTable/MobileDisclose.tsx
- client/src/components/molecules/LeaveManagementResultTable/index.tsx
- client/src/components/molecules/ListOfLeaveTable/MobileDisclose.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
- client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx
- client/src/components/molecules/NotificationList/NotificationItem.tsx
- client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx
- client/src/components/molecules/UserMenuDropdown/index.tsx
- client/src/components/organisms/Drawer/index.tsx
- client/src/components/organisms/Sidebar/index.tsx
- client/src/pages/_document.tsx
- client/src/pages/leave-management/leave-summary.tsx
- client/src/pages/leave-management/yearly-summary.tsx
- client/src/pages/my-leaves.tsx
- client/src/utils/generateData.ts
- client/tailwind.config.js
- https://framgiaph.backlog.com/view/HRIS-125
N/A
cd `client` && `npm run dev`
cd `api` && `dotnet run watch`
- It should now have an accordion mobile disclose in My leave, Yearly summary and Leave summary
- Changed general font into `Poppins` font
[accordion.webm](https://user-images.githubusercontent.com/108642414/220076380-5e4558eb-564b-4300-97b2-9d6c502e6f3a.webm)
> HRIS-125 [BugTask] Change table to accordion in My leave, Yearly summary and Leave summary

- api/Context/HrisContext.cs
- api/Entities/Leave.cs
- api/Enums/NotificationTypeEnum.cs
- api/Enums/RequestStatusEnum.cs
- api/Migrations/20230222054212_ModifyNotificationDiscriminator.Designer.cs
- api/Migrations/20230222054212_ModifyNotificationDiscriminator.cs
- api/Program.cs
- api/Schema/Queries/NotificationQuery.cs
- api/Services/LeaveService.cs
- api/Services/NotificationService.cs
https://framgiaph.backlog.com/view/HRIS-133
- Notification related data is all stored in the `data` column of Notification table in string of JSON
- If you encounter error in updating your database, try to delete the rows not generated by seeder in the `Leave` table
- run `dotnet ef database update`
- run `docker compose up`
- use the following query
```
query($id: Int!) {
notificationByRecipientId(id: $id){
id
type
data
readAt
isRead
}
}
```
- use the following variable
```
{
"id": 4
}
```
- The query should return list of notifications for the recipient
- `Data` column of the Notification table should contain more necessary data
- Sample query
- New Notifications table
> HRIS-133 [BE] Implement Fetch notifications for the authenticated user functionality

- api/Seeders/DatabaseSeeder.cs
- client/src/components/molecules/NotificationPopOver/index.tsx
https://framgiaph.backlog.com/view/HRIS-123
- only fixes
- go to any page/tab of `Leave Management`
- When the user clicked `See all notifications` button from the notification bell, the user should be properly redirected to Notifications page
[Notification fix.webm](https://user-images.githubusercontent.com/111718037/221745210-57d5e5bd-e695-423d-b479-993b42715f54.webm)
> HRIS-123-01 [FE] Fixed routing from Leave Management pages to Notifications page

- client/src/components/molecules/NotificationFilterDropdown/index.tsx
- client/src/pages/notifications.tsx
- client/src/utils/constants/notificationFilter.ts
https://framgiaph.backlog.com/view/HRIS-134
- go to `http://localhost:3000/notifications`
- perform filter using the `Filters` button
- at first visit of page, the URL should have no queries
- after filtering, filter parameters should be present in the URL
- filter parameters and result should persist even after page reload
[Filter.webm](https://user-images.githubusercontent.com/111718037/221782513-d7ec0c9d-9d56-4583-91d7-77f80d2cf471.webm)
> HRIS-134 [FE] Implement Filter notifications functionality

- api/Enums/InputValidationMessageEnum.cs
- api/Enums/NotificationTypeEnum.cs
- api/Enums/ProjectEnum.cs
- api/Program.cs
- api/Requests/ApproveLeaveUndertimeRequest.cs
- api/Requests/ApproveOvertimeRequest.cs
- api/Schema/Mutations/ApprovalMutation.cs
- api/Services/ApprovalService.cs
- api/Services/NotificationService.cs
- api/Utils/Validation.cs
- api/api.csproj
https://framgiaph.backlog.com/view/HRIS-145
https://framgiaph.backlog.com/view/HRIS-147
- This is combined PR for Tasks HRIS-145 and HRIS-147
- run these mutations one-by-one, uncomment mutations
```
mutation($overtimeApprovalManager: ApproveOvertimeRequestInput!){
approveDisapproveOvertime(approvingData: $overtimeApprovalManager)
}
```
- variables, change values using data from your database (note: `userId` is the id of approving leader/manager)
```
{
"overtimeApprovalManager": {
"userId": 70,
"overtimeId": 1018,
"isApproved": true,
"approvedMinutes": 123
},
"overtimeApprovalLeader": {
"userId": 2,
"notificationId": 2076,
"isApproved": true
},
"leaveApproval": {
"userId": 70,
"notificationId": 4079,
"isApproved": …
```
> HRIS-145 [BE] Implement Approve or Disapprove overtime, leave, and undertime functionality

- client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
- client/src/graphql/mutations/leaveMutation.ts
- client/src/hooks/useLeave.ts
https://framgiaph.backlog.com/view/HRIS-146
- go to `http://localhost:3000/notifications`
- Approve/Disapprove an Undertime request
- Approving and disapproving of undertime requests should work now
> HRIS-146-01 [FE] Fix Approve/Disapprove of Undertime Requests

- api/DTOs/MyOvertimeDTO.cs
- api/Schema/Queries/OvertimeQuery.cs
- api/Services/OvertimeService.cs
- client/src/components/molecules/MyOvertimeTable/DesktopTable.tsx
- client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx
- client/src/components/molecules/MyOvertimeTable/ShowRemarksModal.tsx
- client/src/components/molecules/MyOvertimeTable/YearlyFilterDropdown.tsx
- client/src/components/molecules/MyOvertimeTable/columns.tsx
- client/src/components/molecules/MyOvertimeTable/index.tsx
- client/src/components/organisms/Header/index.tsx
- client/src/graphql/queries/overtimeQueries.ts
- client/src/hooks/useOvertimeQuery.ts
- client/src/pages/my-overtime.tsx
- client/src/utils/constants/dummyMyOvertimeData.ts
- client/src/utils/interfaces/index.tsx
- client/src/utils/myOvertimeHelpers.ts
https://framgiaph.backlog.com/view/HRIS-150
https://framgiaph.backlog.com/view/HRIS-149
- I fixed and added the `supervisor` columns in the table and follow code implementation of sir Nilo
- #116 
- #113 
cd `api` && dotnet run watch
cd `client` && `npm run dev`
- It should now filter the MyOvertime data based on `year` and `status` -> ['pending', 'disapproved', 'approved']
[filtering.webm](https://user-images.githubusercontent.com/108642414/224582831-abd54f48-de67-4488-aba9-fb765158f4a1.webm)
> HRIS-150 [BE/FE] Implement and Integrate filter list be Pending, Approved and Rejected functionality for My Overtime Page

- client/src/components/molecules/OvertimeManagementTable/columns.tsx
- client/src/pages/overtime-management.tsx
- client/src/utils/interfaces/index.tsx
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-153#comment-140059876)
run docker
login to a manager's account
http://localhost:3000/overtime-management
- Button should not be dependent on the status
- If only one project exists, it should still have a dropdown
> HRIS-151/153 [BE/FE] HR Admin and Manager project dropdown and action buttons

- api/Context/HrisContext.cs
- api/DTOs/OvertimeDTO.cs
- api/DTOs/TimeEntriesSummaryDTO.cs
- api/DTOs/TimeEntryDTO.cs
- api/DTOs/UserDTO.cs
- api/Enums/WorkStatusEnum.cs
- api/Migrations/20230315070132_AvatarSeeder.Designer.cs
- api/Migrations/20230315070132_AvatarSeeder.cs
- api/Seeders/DatabaseSeeder.cs
- api/Services/TimeSheetService.cs
- api/Services/UserService.cs
- client/src/components/atoms/Chip/index.tsx
- client/src/components/molecules/DTRManagementTable/DesktopTable.tsx
- client/src/components/molecules/DTRSummaryTable/columns.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/DesktopTable.tsx
- client/src/utils/constants/work-status.ts
https://framgiaph.backlog.com/view/HRIS-160
- Seeder for user avatar is just added on this task
- copy `deafult.png` from `api/wwwroot/static/avatar` to `api/wwwroot/media/avatar`
- run `dotnet ef database update` in `api` directory
- go to MyDTR and DTR Management Page
- New values should reflect in Leave, Absences, Undertime and Overtime in DTR tables
- There should be new Status in time entries
- In the DB, there should be new rows in `Media` table for user avatars
- MyDTR
- DTR Summary
- Media table in DB
> HRIS-160 [BE/FE] Implement and Integrate changes to DTR and My DTR page when there is a leave, undertime and overtime entry

- api/DTOs/MyOvertimeDTO.cs
- client/src/components/molecules/MyOvertimeTable/columns.tsx
https://framgiaph.backlog.com/view/HRIS-165
- Fix on My Overtime page
- Run ``` docker compose up --build ```
- Shows data on the RequestedHours column
- Reflects 0 RequestedHours if request got disapproved
> HRIS-165 [BugTask] Fetch data in requested hours in My Overtime

- api/Entities/MultiProject.cs
- api/Enums/NotificationTypeEnum.cs
- api/Requests/ApproveChangeShiftRequest.cs
- api/Schema/Mutations/ApprovalMutation.cs
- api/Schema/Mutations/ChangeShiftMutation.cs
- api/Services/ApprovalService.cs
- api/Services/ChangeShiftService.cs
- api/Services/NotificationService.cs
- api/Utils/Validation.cs
https://framgiaph.backlog.com/view/HRIS-174
- to approve/disapprove change shift request, run this mutation
```
mutation($changeShiftApproval: ApproveChangeShiftRequestInput!){
approveDisapproveChangeShift(approvingData: $changeShiftApproval)
}
{
"changeShiftApproval": {
"userId": 70,
"notificationId": 4033,
"isApproved": true
}
}
```
- to watch for notifications, run this subscription
```
subscription {
changeShiftCreated(id: 4) {
id
type
data
readAt
isRead
}
}
```
- Project Leader/s can approve a change shift request
- Manager will only receive notification for approval if all project leaders have approved.
- Once the manager approved, `StartTime` and `EndTime` in `TimeEntries` table will be updated
- Once the …
> HRIS-174 [BE] Implement approve or disapprove change shift request functionality

- client/src/components/molecules/FiledOffsetModal/FileOffsetModal.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/AddNewOffsetModal.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/ChangeShiftDetails.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/ChangeShiftResolved.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/LeaveDetails.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/LeaveResolvedDetails.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/OffsetScheduleDetails.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/OvertimeDetails.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/OvertimeResolvedDetails.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/ResolvedDetails.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/UndertimeDetails.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/UndertimeResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
- client/src/components/organisms/Header/index.tsx
- client/src/graphql/mutations/eslOffsetMutation.ts
- client/src/graphql/queries/UserQuery.ts
- client/src/graphql/subscriptions/eslOffsetSubscription.ts
- client/src/hooks/useOffsetForESL.ts
- client/src/hooks/useUserQuery.ts
- client/src/pages/notifications.tsx
- client/src/utils/constants/notificationTypes.ts
- client/src/utils/createLeaveHelpers.ts
- client/src/utils/interfaces/eslOffsetInterface.ts
https://framgiaph.backlog.com/view/HRIS-182
- Make sure that your position is 5 which is the user position of ESL Teacher to show the dropdown
BE #147 
- go to `http://localhost:3000/my-daily-time-record
- to create request click the action dropdown name `ESL Offset Schedule`
- only ESL Teachers should be able to create request
- after creating a request, a notification should be created and sent to the Team Leader
- the `allESLUsers` data will display in the Team Leaders React Select dropdown list
- ESL Teacher can now be able to request and offset based on the form provided
[recording.webm](https://user-images.githubusercontent.com/108642414/229034773-e53b082f-e9bb-4f7a-a431-0753c42a7a34.webm)
> HRIS-182 [FE] Integrate change schedule as an offset functionality for ESL Teacher

- api/Requests/ApproveESLChangeShiftRequest.cs
- api/Schema/Mutations/ESLChangeShiftMutation.cs
- api/Services/ApprovalService.cs
- api/Services/ChangeShiftService.cs
- api/Services/NotificationService.cs
- api/Utils/Validation.cs
https://framgiaph.backlog.com/view/HRIS-176
- There should be an existing ESL Change shift request
- Inside the API directory, run ``` dotnet run ```
- To test:
```
mutation ($request: ApproveESLChangeShiftRequestInput!) {
approveDisapproveESLChangeShiftStatus(request: $request){
id
}
}
```
```
{
"request": {
"managerId" : 57,
"notificationId" : 2019,
"isApproved" : true
}
}
```
```
subscription {
eslChangeShiftCreated(id: 4) {
type
data
readAt
isRead
}
}
```
- It should alter the Status value inside the Notifications.Data to approved or disapproved
- It should send a notification after the disapproval
- It should alter the StartTime and EndTime inside TimeEntries table
https://user-images.githubusercontent.com/109492180/229072923-08d589d6-05ae-4149-89fb-9746d4e95a27. …
> HRIS-176 [BE] Implement approve or disapprove change offset request functionality

- client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
- client/src/components/molecules/DTRManagementTable/columns.tsx
- client/src/components/molecules/NotificationList/NotificationItem.tsx
- client/src/components/molecules/NotificationPopOver/index.tsx
- client/src/components/organisms/Header/index.tsx
Backlog Link
run docker 
In the notification menu time differ in the page
Remove the hr in the notification if change shift
Filed offset should only display if your ESL
> HRIS-184 [BugTask] Time in the notification menu and page are not same

- client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
- client/src/components/molecules/DTRManagementTable/columns.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
https://framgiaph.backlog.com/view/HRIS-184
- revision PR of #153 
- go to `MyDTR`/`DTRManagement` page and click the `Action` menu
- `Filed Offset` option should be in the option list in `DTRManagement` page
- There should be no `Vertical Ellipsis` tooltip on Action button in MyDTR and DTRManagement pages
> HRIS-184-02 [FE] Readded Filed Offset Modal in DTR Management page

- client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
- client/src/components/molecules/NotificationPopOver/index.tsx
- client/src/graphql/mutations/eslOffsetMutation.ts
- client/src/hooks/useOffsetForESL.ts
- client/src/utils/interfaces/eslOffsetInterface.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-177)
npm run dev, docker run or run docker
Create an offset request as an ESL teacher (Position ID: 5)
Go to the assigned leader that will approve / disapprove offset.
Go to the notifications and approve / disapprove the request.
ESL Leaders can approve / disapprove filed ESL Offset request of an ESL teacher
Dissaproved
Approved
> HRIS-177 [FE] Integrate approve or disapprove change offset request functionality

- api/Schema/Mutations/ESLOffsetMutation.cs
- api/Services/ApprovalService.cs
- api/Services/ESLChangeShiftService.cs
- api/Services/NotificationService.cs
- api/Utils/Validation.cs
https://framgiaph.backlog.com/view/HRIS-179
- Existing Offset & Notification for that offset
- To test:
```
mutation ($request: ApproveESLChangeShiftRequestInput!) {
approveDisapproveChangeOffsetStatus(request: $request){
id
}
}
```
```
{
"request": {
"teamLeaderId" : 57,
"notificationId" : 3113,
"isApproved" : true
}
}
```
```
subscription {
eslOffsetCreated(id: 4) {
type
data
readAt
isRead
}
}
```
- It should be able to approve and disapprove requests.
- Reflect the changes on the TimeEntries table
- Send new notification with Type: "offset_resolved"
https://user-images.githubusercontent.com/109492180/229463306-c06474ae-268f-4686-9a89-d70e51123eca.mp4
> HRIS-179 [BE] Implement approve or disapprove offset request filed functionality

- client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
- client/src/graphql/mutations/eslOffsetMutation.ts
- client/src/hooks/useOffsetForESL.ts
- client/src/utils/constants/notificationTypes.ts
- client/src/utils/interfaces/eslOffsetInterface.ts
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-180)
run docker or run your localhost
In your graphql playground input these values to create an offset
```
mutation ($request: CreateESLOffsetRequestInput!) {
createESLOffset(request: $request){
id
}
}
```
```
{
"request": {
"userId" : 4,
"teamLeaderId" : 1,
"timeEntryId" : 4,
"timeIn" : "09:00",
"timeOut" : "14:00",
"description" : "test description",
"title": "title 2"
}
}
```
Login with the teamleader you assigned.
Go to the notifications and click on view details
Approve or disapprove the offset.
ESL Team leader can approve/disapprove offset for ESL teachers
Table Plus data
> HRIS-180 [FE] Integrate approve or disapprove offset request filed functionality

- client/src/components/molecules/NotificationList/NotificationTypeDetails/OffsetResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
- client/src/utils/constants/notificationTypes.ts
- https://framgiaph.backlog.com/view/HRIS-183
- Revision task #158 
- run `client && npm run dev`
- run `api && dotnet run watch`
- A recipient will now be able to view the details of Offset Resolved Details  
[notifOffset.webm](https://user-images.githubusercontent.com/108642414/230042120-21514174-3623-4db4-8980-609fe20cf4cd.webm)
> HRIS-183-01 [FE] Fix Notification Offset Resolved Details

- api/DTOs/ChangeShiftDTO.cs
- api/DTOs/ESLChangeShiftDTO.cs
- api/DTOs/TimeEntryDTO.cs
- api/Services/TimeSheetService.cs
https://framgiaph.backlog.com/view/HRIS-186
- run query
```
query ($id: Int!) {
timeEntriesByEmployeeId(id: $id) {
id
date
timeIn {
id
timeHour
remarks
createdAt
}
timeOut {
id
timeHour
remarks
createdAt
}
startTime
endTime
workedHours
trackedHours
late
undertime
overtime {
requestedMinutes
approvedMinutes
isLeaderApproved
isManagerApproved
}
status
changeShift{
id
manager{
name
}
timeIn
timeOut
description
}
eslChangeShift{
id
teamLeader{
name
}
timeIn
timeOut
description
}
}
}
}
#Variable
{
"id":4
}
```
- There should be `changeShift` and `eslChangeShift` in the time entry query result
- Sample Query
> HRIS-186 [BE] Implement view filed change shift for ESL and Non-ESL functionality

- client/src/components/molecules/InterruptionTimeEntriesModal/index.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/AddNewOffsetModal.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/ChangeShiftRequestModal.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/ViewFiledChangeShiftModal/ChangeShiftDetails.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/ViewFiledChangeShiftModal/ESLChangeShiftDetails.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/ViewFiledChangeShiftModal/index.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
- client/src/components/molecules/NotificationList/NotificationTypeDetails/ESLChangeShiftDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/ChangeShiftDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/ChangeShiftResolved.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/ESLChangeShiftDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/LeaveDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/LeaveResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/OffsetDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/OffsetResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/OffsetScheduleDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/OvertimeDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/OvertimeResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/ResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/UndertimeDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/UndertimeResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/index.tsx
- client/src/graphql/queries/timesheetQueries.ts
- client/src/hooks/useChangeShift.ts
- client/src/hooks/useOffsetForESL.ts
- client/src/utils/constants/notificationTypes.ts
- client/src/utils/types/timeEntryTypes.ts
- https://framgiaph.backlog.com/view/HRIS-187
- #162 
- Refactor Mobile Disclose My daily time Record Table that moved outside the Disclose Component due to the fact that it will eventually getting darker the bg of Modal when multiple Disclose open 
- ESL and Non-ESL User will now be able to view the requested File Change
- Previous integration also work fine when filing  change shift request
[filing.webm](https://user-images.githubusercontent.com/108642414/231392714-498cede5-46af-4fe2-b9ea-4f9643f9588d.webm)
> HRIS-187 [FE] Integrate view filed change shift for ESL and Non-ESL functionality

- api/DTOs/EmployeeScheduleDTO.cs
- api/Enums/DaysOfTheWeekEnum.cs
- api/Program.cs
- api/Requests/EmployeeScheduleRequest.cs
- api/Schema/Queries/EmployeeScheduleQuery.cs
- api/Services/EmployeeScheduleService.cs
https://framgiaph.backlog.com/view/HRIS-197
- Go to ``` http://localhost:5257/graphql/ ```
```
query {
allEmployeeScheduleDetails {
id
scheduleName
days {
isDaySelected
workingDay
timeIn
timeOut
}
}
}
```
```
query ($employeeScheduleId: Int!) {
employeeScheduleDetails(employeeScheduleId: $employeeScheduleId) {
scheduleName
days {
isDaySelected
workingDay
timeIn
timeOut
}
}
}
```
```
{
"employeeScheduleId": 1
}
```
- It should fetch the list of schedule available in the database
> HRIS-197 [BE] Implement display schedule functionality

- api/DTOs/ESLOffsetDTO.cs
- api/NotificationDataClasses/ChangeShiftData.cs
- api/Services/ApprovalService.cs
- api/Services/NotificationService.cs
https://framgiaph.backlog.com/view/HRIS-192
- To create ESL change shift request, refer to this PR #147 
- Also fixed the `type` of approved/disapproved ESLChangeShift notification
- You can also approve/disapprove through the notifications in FE
- `Offsets` object inside ESLChangeShift notification data is a list with the following attibutes: 
```
Id
UserId
TimeEntryId
TeamLeaderId
TimeIn
TimeOut
Title
Description
IsLeaderApproved
IsUsed
```
- to approve/disapprove a request, use the following mutation
```
mutation ($request: ApproveESLChangeShiftRequestInput!) {
approveDisapproveESLChangeShiftStatus(request: $request){
id
}
}
{
"request": {
"teamLeaderId" : 3,
"notificationId" : 9052,
"isApproved" : false
}
}
``` …
> HRIS-192 [BE] Modify display of ESL Change Shift and Notification Approve/Disapprove Functionality

- api/Enums/ErrorMessageEnum.cs
- api/Enums/InputValidationMessageEnum.cs
- api/Enums/SuccessMessageEnum.cs
- api/Program.cs
- api/Requests/CreateEmployeeScheduleRequest.cs
- api/Requests/EmployeeScheduleRequest.cs
- api/Requests/WorkingDayTimesRequest.cs
- api/Schema/Mutations/EmployeeScheduleMutation.cs
- api/Services/EmployeeScheduleService.cs
- api/Utils/Validation.cs
https://framgiaph.backlog.com/view/HRIS-193
- Backend integration only
- In the api directory run ``` dotnet run ```
- To create a new Schedule, run the following mutations from your playground ``` http://localhost:5257/graphql/ ```
```
mutation ($request: CreateEmployeeScheduleRequestInput!) {
createEmployeeSchedule(request: $request){
}
}
```
```
{
"request": {
"userId": 57,
"scheduleName": "Graveyard Shift",
"workingDays": [
{
"day": "Monday",
"from": "09:30",
"to": "18:30"
},
{
"day": "Wednesday",
"from": "09:30",
"to": "18:30"
},
{
"day": "Thursday",
"from": "09:30",
"to": "18:30"
}
]
}
}
```
- It should create a new Employee Schedule in the EmployeeSchedule table
- It should create new data inside the WorkingDayTimes table
- It should check if
- the user is an HR Admin
- the …
> HRIS-193 [BE] Implement Create Schedule Functionality

- client/src/components/molecules/NotificationList/ViewDetailsModal/ESLChangeShiftDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/index.tsx
- client/src/components/organisms/Header/index.tsx
- client/src/pages/notifications.tsx
- client/src/utils/constants/notificationTypes.ts
- client/src/utils/interfaces/eslOffsetInterface.ts
- client/src/utils/interfaces/index.tsx
- client/src/utils/types/notificationTypes.ts
https://framgiaph.backlog.com/view/HRIS-200
- There should be existing approved `ESLOffset` data
- Approve/Disapprove can be done with 2 accounts
- Approve/Disapprove is optional in this PR, if you already have existing ESL Change Shift notification, that will do.
- If there is no ESL Change Shift request yet, create one in `My Daily Time Record` page
- then go to notification page of the recipient of the request, `http://localhost:3000/notifications`
- View the notification details, then approve/disapprove
- then go back to the sender's notification page
- There should be `Offsets` in the notification details of ESL Change Shift notification (request/approve/disapprove)
[ModifiedESLChangeShiftDisplay.webm](https://user-images.githubusercontent.com/1117180 …
> HRIS-200 [FE] Integrate the modified display of ESL Change Shift and Notification Approve/Disapprove Functionality

- api/Enums/ErrorMessageEnum.cs
- api/Enums/InputValidationMessageEnum.cs
- api/Enums/SuccessMessageEnum.cs
- api/Requests/UpdateEmployeeScheduleRequest.cs
- api/Schema/Mutations/EmployeeScheduleMutation.cs
- api/Services/EmployeeScheduleService.cs
- api/Utils/Validation.cs
https://framgiaph.backlog.com/view/HRIS-195
```
mutation ($request: UpdateEmployeeScheduleRequestInput!) {
updateEmployeeSchedule(request: $request){
}
}
```
```
{
"request": {
"userId": 57,
"employeeScheduleId": 2057,
"scheduleName": "Graveyard Shift stone!",
"workingDays": [
{
"day": "Monday",
"from": "10:30",
"to": "18:30"
},
{
"day": "Wednesday",
"from": "11:30",
"to": "18:30"
},
{
"day": "Thursday",
"from": "12:30",
"to": "18:30"
}
]
}
}
```
- If the name is being edited, it should change the Name of the employee schedule in the EmployeeSchedules table
- If the days and times are being edited, it should update the data inside the WorkingDayTimes table base on the changes the user made
- It should checks if:
- …
> HRIS-195 [BE] Implement edit schedule details functionality

- client/src/components/atoms/TabLink/index.tsx
- client/src/components/molecules/ViewScheduleMembersModal/MemberList.tsx
- client/src/components/molecules/ViewScheduleMembersModal/index.tsx
- client/src/components/templates/ModalTemplate/ModalHeader.tsx
- client/src/pages/schedule-management.tsx
- client/src/utils/constants/dummyScheduleMembers.ts
- client/src/utils/interfaces/scheduleMemberInterface.ts
- https://framgiaph.backlog.com/view/HRIS-208
Figma Design
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?node-id=2576-28630&t=jhFnYMvC5XGJg7j5-4
- It should now have a markup modal for View Schedule Members
- Simple Client Side Search Functionality of a Members
[modal.webm](https://user-images.githubusercontent.com/108642414/234168144-c0b9ca86-ae21-44e0-9f04-10cd05bddc14.webm)
[animated tab.webm](https://user-images.githubusercontent.com/108642414/234168270-07056046-f62e-4961-91b3-202880014a04.webm)
> HRIS-208 [Markup] Create Schedule Modal

- api/DTOs/EmployeeScheduleDTO.cs
- api/Services/EmployeeScheduleService.cs
- client/src/components/molecules/ViewScheduleMembersModal/index.tsx
- client/src/graphql/queries/employeeSchedule.ts
- client/src/hooks/useEmployeeSchedule.ts
- client/src/pages/schedule-management.tsx
- client/src/utils/constants/fetchStatus.ts
- client/src/utils/types/employeeScheduleTypes.ts
https://framgiaph.backlog.com/view/HRIS-210
- Added `memberCount` in the `getEmployeeScheduleQuery` query result, both in the FE and BE
- as an `Admin`, go to `Schedule Management` page
- Select a schedule and click the button on the upper right to open the modal
- The button should display the number of employees that belongs to that schedule
- There should be a loading state when fetching is not yet done
- The modal should display the list of all employees that belongs to that schedule
- There should be `No Data Available` message if there are no employees in that schedule
- If user is offline or fetch failed, there should be `Error Fetching Data` message
https://user-images.githubusercontent.com/111718037/234492159-ce3ab329-5e02-4bfc-8f46-e76bc62eea36.m …
> HRIS-210 [FE] Implement UI feature to display list of employees assigned to a selected schedule

- api/Enums/ErrorMessageEnum.cs
- api/Enums/SuccessMessageEnum.cs
- api/Requests/DeleteEmployeeScheduleRequest.cs
- api/Schema/Mutations/EmployeeScheduleMutation.cs
- api/Services/EmployeeScheduleService.cs
- api/Utils/Validation.cs
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-222)
Go to : `http://localhost:5257/graphql/`
Operations:
```
mutation ($request: DeleteEmployeeScheduleRequestInput!) {
deleteEmployeeSchedule(request: $request)
}
```
##user Id must be HRAdmin
Variables:
```
{
"request": {
"userId": 1,
"employeeScheduleId": 1
}
}
```
Proof:
[screen-capture.webm](https://user-images.githubusercontent.com/109579325/234487863-e9dd25d4-a069-4398-b46f-ecc4a829e4cd.webm)
> HRIS-222 [BE] Implement remove schedule functionality

- api/Requests/SearchEmployeesByScheduleRequest.cs
- api/Schema/Queries/EmployeeScheduleQuery.cs
- api/Services/EmployeeScheduleService.cs
https://framgiaph.backlog.com/view/HRIS-219
- (docker) run `docker compose up --build`
- (local) run `dotnet run`
- use the following query
```
query($request: SearchEmployeesByScheduleRequestInput!) {
searchEmployeesBySchedule (request: $request) {
id
name
avatarLink
position{
name
}
isOnline
}
}
{
"request": {
"employeeScheduleId": 1001,
"searchKey": "sample"
}
}
```
- The query should return employees that belongs to schedule with id equal to `employeeScheduleId` and the name, email or positions contains the string from variable `searchKey`
https://user-images.githubusercontent.com/111718037/234754667-6d02caeb-e456-4858-bb9b-8bc3b3b5cadc.mp4
> HRIS-219 [BE] Implement search employee functionality

- client/src/components/molecules/ViewScheduleMembersModal/index.tsx
- client/src/graphql/queries/employeeSchedule.ts
- client/src/hooks/useEmployeeSchedule.ts
- client/src/utils/types/employeeScheduleTypes.ts
https://framgiaph.backlog.com/view/HRIS-220
- this integration replaced the query `getEmployeesByScheduleQuery` to `getSearchEmployeesByScheduleQuery` in `ViewScheduleMembersModal` component because it behaves the same at initial load of modal
- (docker) run `docker compose up --build`
- (local FE) run `npm run dev`
- (local BE) run `dotnet run`
- As an `admin`, go to `Schedule Management` page and click the `View all members` button on the upper right
- In the text area, enter your search key
- Search key should be debounced and the query will only start after a pause on keypress
- Search key should be case-insensitive
- There should be a loading indicator while the fetching is in progress
- The search result should be employees that has the search key in the name, email or position in …
> HRIS-220 [FE] Integrate search employee functionality

- api/Enums/SuccessMessageEnum.cs
- api/Requests/UpdateMemberScheduleRequest.cs
- api/Schema/Mutations/EmployeeScheduleMutation.cs
- api/Services/EmployeeScheduleService.cs
- api/Utils/Validation.cs
https://framgiaph.backlog.com/view/HRIS-217
- In the api directory, ``` dotnet run ```
- To test the pr, run this mutation:
```
mutation ($request: UpdateMemberScheduleRequestInput!) {
updateMemberSchedule(request: $request)
}
```
```
{
"request": {
"userId": 57,
"employeeId": 1,
"scheduleId": 1001
}
}
```
- It should change the scheduleId of that specific user
- Returns error(s) if input(s) is/are invalid
- Returns success message if the query went through
https://user-images.githubusercontent.com/109492180/235048981-779541f4-5798-46fe-90aa-376b94d737fa.mp4
> HRIS-217 [BE] Implement re-assign employee schedule functionality

- client/src/pages/overtime-management.tsx
- https://framgiaph.backlog.com/view/HRIS-224
- For Developer: Please be careful to change single utility
- The current problem was related to the inability of the page to display horizontal scroll, which made it difficult for users to navigate through the content
- Overtime Management Page will now have horizontal scrollabar
- To resolve the horizontal scroll issue, I implemented a fix by changing `h-screen` to `h-full`  utility property to the Overtime Management Page. The proposed will be testing through rigorous quality assurance testing to ensure that it does not impact any other functionality of the page.
[overtime scrollable …
> HRIS-224 [Bugfix] Add Horizontal Scrollbar to Overtime Management Page

- client/src/components/templates/ScheduleManagementLayout/ScheduleList/ScheduleItem.tsx
- client/src/components/templates/ScheduleManagementLayout/ScheduleList/index.tsx
- client/src/components/templates/ScheduleManagementLayout/ScheduleListModal.tsx
- client/src/components/templates/ScheduleManagementLayout/index.tsx
- client/src/hooks/useScreenCondition.ts
- client/src/pages/schedule-management.tsx
- https://framgiaph.backlog.com/view/HRIS-226
- https://framgiaph.backlog.com/view/HRIS-227
- I will create another figma design for this new UI that I implemented
-  HR/Admin will only be able to click the Schedule Icon Button during Mobile/Table Mode
- Fixed Loading Indicator when triggering the delete schedule confirmation 
- Schedule Sidebar list enable scrolling when there are many schedules created 
- Insures all existing functionality is still working
[record.webm](https://user-images.githubusercontent.com/108642414/236105093-e2a97da5-0472-49f2-a146-e8f4aa5f277f.webm)
> HRIS-226 [Bugfix] Enable scrolling for the schedule list on the Schedule Management page when there are many schedules created

- client/src/components/molecules/EmployeeManagementTable/columns.tsx
https://framgiaph.backlog.com/view/HRIS-228
run docker or npm run dev and dotnet run
go to http://localhost:3000/employee-management
Disable stretch functionality for the Employee Management page.
Proof:
[screen-capture (2).webm](https://user-images.githubusercontent.com/109579325/236107735-42ad8d23-93af-40d1-9fff-145dd12d08c9.webm)
> HRIS-228 [Bugfix] Disable stretch functionality for the Employee Management page.

- client/src/components/atoms/Buttons/ButtonLink.tsx
- https://framgiaph.backlog.com/view/HRIS-231
N/A
- Sidebar submenu will no longer trigger a loading indicator
[loading.webm](https://user-images.githubusercontent.com/108642414/236109119-647996c1-ccf6-4094-8d4b-dd59dfafe2a8.webm)
> HRIS-231 [Bugfix] Disable loading indicator for sidebar sub menu button

- api/Enums/MiddlewareErrorMessageEnum.cs
- api/Middlewares/AdminUser.cs
- api/Middlewares/Attributes/AdminUserAttribute.cs
- api/Middlewares/Attributes/AuthorizeUserAttribute.cs
- api/Middlewares/Attributes/ESLUserAttribute.cs
- api/Middlewares/Attributes/ManagerUserAttribute.cs
- api/Middlewares/Attributes/NonESLUserAttribute.cs
- api/Middlewares/AuthorizeUser.cs
- api/Middlewares/ESLUser.cs
- api/Middlewares/ManagerUser.cs
- api/Middlewares/NonESLUser.cs
- api/Program.cs
- api/Schema/Mutations/ChangeShiftMutation.cs
- api/Schema/Mutations/ESLChangeShiftMutation.cs
- api/Schema/Mutations/ESLOffsetMutation.cs
- api/Schema/Mutations/EmployeeScheduleMutation.cs
- api/Schema/Queries/EmployeeScheduleQuery.cs
- api/Schema/Queries/LeaveQuery.cs
- api/Schema/Queries/TimeSheetQuery.cs
- client/src/pages/sign-in.tsx
- client/src/utils/customHttpHeaders.ts
- client/src/utils/shared/client.ts
https://framgiaph.backlog.com/view/HRIS-229
- This task affects all queries and mutations, it might need thoroughly testing
- `nextauth-token` should now be present in headers of every http requests
- (docker) run `docker compose up --build`
- (local FE) run `npm run dev`
- (local BE) run `dotnet run`
- if currently signed-in, logout first then sign-in again
- To test `Admin Only` function, you can run this query
```
query($request: SearchEmployeesByScheduleRequestInput!) {
searchEmployeesBySchedule (request: $request) {
id
name
avatarLink
position{
name
}
isOnline
}
}
{
"request": {
"employeeScheduleId": 1,
"searchKey": "teacher"
}
}
nextAuth-token: <input your token from Personal_Access_Token table in DB>
```
- To test `ESL Only` function, you …
> HRIS-229 [BE] Implement Backend Authentication and Authorization

- client/src/components/atoms/Buttons/ButtonLink.tsx
- client/src/components/molecules/NavList/index.tsx
- https://framgiaph.backlog.com/view/HRIS-232
- N/A
- When the side menu icon clicked into the tab pages menu, the first tab page will be redirected
- Clicking `My Forms` button in sidebar or its container should display it submenus
- Clicking `Leave Management` button in sidebar or its container should display it submenus
- Clicking the main menu should display the submenu if it's not open yet and if it's already open clicking it again will collapse the the submenus
[expand.webm](https://user-images.githubusercontent.com/108642414/236158115-5b0f389d-363c-4fba-b74d-6bbfae0f885f.webm)
> HRIS-232 [Bug] Fix expand fixture of menu with sub menu

- client/src/pages/notifications.tsx
https://framgiaph.backlog.com/view/HRIS-230
- go to Notifications page or `http://localhost:3000/notifications`
- Approved notifications now also included in the selected filter type
https://user-images.githubusercontent.com/111718037/236161295-5df5ebd8-740b-4ae7-877b-ac773f90e337.mp4
> HRIS-230 [Bugfix] Display the desired filter type in the notification filters function

- api/DTOs/UserDTO.cs
- api/Enums/ErrorMessageEnum.cs
- api/NotificationDataClasses/LeaveData.cs
- api/Services/ApprovalService.cs
- api/Services/NotificationService.cs
- client/src/components/molecules/AddNewLeaveModal/LeaveTab.tsx
- client/src/components/organisms/Header/index.tsx
- client/src/graphql/queries/UserQuery.ts
- client/src/hooks/useLeave.ts
- client/src/utils/types/userTypes.ts
https://framgiaph.backlog.com/view/HRIS-225
- BE and FE bugfix
- Manager and Leader should approve the leave to see the update on the counter
- We can add a tooltip on the disabled WithPay option
- There should be a pending leave request
- Upon the approval of the Manager/Leader, the PaidLeaves column on the Users table will be updated if isWithPay option is enabled
- It should update the value of the column PaidLeaves on the Users table if isWithPay option is enabled
- It should do a live update on FE upon approval
https://user-images.githubusercontent.com/109492180/236162192-65e68aaf-81b5-45f5-888b-42cf3ec3a3b0.mp4
https://user-images.githubusercontent.com/109492180/236162486-91f3da01-cc63-4f68-8b00-2f23b6108706.mp4
https://user-images.githubusercontent.com/109492180/236162696-31c513a8-9 …
> HRIS-225 [Bugfix] Update Leave Count when Leave is Filed

- client/src/pages/notifications.tsx
https://framgiaph.backlog.com/view/HRIS-246
- Bugtask only
- In the root directory run ``` docker compose up ```
- Go to ``` http://localhost:3000/notifications ```
- It should display the notification page without error, with or without existing notification(s)
https://user-images.githubusercontent.com/109492180/237031495-2c27c41f-35fe-4c9e-804a-38bfcd3443f7.mp4
> HRIS-246 [Bugfix] Resolve Error Thrown on Notifications Page Visit

- client/src/components/molecules/NotificationList/NotificationItem.tsx
- client/src/components/molecules/NotificationPopOver/index.tsx
- client/src/components/molecules/ViewScheduleMembersModal/MemberList.tsx
- client/src/components/templates/ModalTemplate/ModalHeader.tsx
https://framgiaph.backlog.com/view/HRIS-253
- A fix pr
- In the root directory run ``` docker compose up ```
- It should fix the broken images border radius on:
- Notification dropdown
- Notification page
- Notification modal
- Schedule modal
https://github.com/framgia/sph-hris/assets/109492180/e8f98156-d610-4508-a7f9-3cae7bf9a096
> HRIS-253-01 [FE] Fix: Changed the border radius for specific pages

- api/Enums/PositionEnum.cs
- api/Migrations/20230512082231_UpdateUser_Project_Position_Seeder.Designer.cs
- api/Migrations/20230512082231_UpdateUser_Project_Position_Seeder.cs
- api/Seeders/DatabaseSeeder.cs
- client/src/components/molecules/AddNewLeaveModal/LeaveTab.tsx
- client/src/components/molecules/AddNewLeaveModal/UndertimeTab.tsx
https://framgiaph.backlog.com/view/HRIS-259
https://framgiaph.backlog.com/view/HRIS-260
- This is PR for combined tasks HRIS-259 and HRIS-260
- I commented out 2 lines from `LeaveTab.tsx` and `UndertimeTab.tsx` so File Leave Modal won't break in FE. Filing leave function shouldn't have been affected.
- run `dotnet ef database update` in `api` directory
- `Quennie Andeza` should be added in User table
- All users should have `12` initial `PaidLeaves` values
- There should have new projects in `Projects` table
- `ProjectLeaderId` should have been updated in `Projects` table
- There should have two new positions in `Positions` table
- New User and New PaidLeave values
- New Projects and Updated Project Leaders
- New Positions
> HRIS-259 [BE] Update the database seeder

- client/src/components/molecules/DTRManagementTable/columns.tsx
- client/src/components/molecules/LegendTooltip/index.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
[Backlog Link](https://framgiaph.backlog.com/view/HRIS-256)
run docker or npm run dev and dotnet run
Move the 'Status' column after the 'Name column in both the DTR Management and My DTR tables to improve user experience.
Replace Beyond 7:30 rendered time in DTR Legends to Beyond 8hrs rendered time.
Proof:
[screen-capture.webm](https://github.com/framgia/sph-hris/assets/109579325/98ff578d-7913-4c7c-80f3-31700d6dd53d)
> HRIS-256 [FE] Make the DTR status visible to both the HR Admin and employee

- api/Services/TimeSheetService.cs
https://framgiaph.backlog.com/view/HRIS-258
- DTR query `timeEntriesByEmployeeId` now return record from latest to oldest
- The change can also be seen immediately in `My Daily Time Record` page in the frontend
- (docker) run `docker compose up db api --build -d`
- try this query
```
query {
timeEntriesByEmployeeId(id: <user_id>) {
id
date
}
}
```
- The query result should have in order from latest to oldest date
https://github.com/framgia/sph-hris/assets/111718037/559c65da-41a7-4146-ac69-89c52d417537
> HRIS-258 [FE/BE] Change the order record for DTR to be latest to oldest

- api/Schema/Mutations/NotificationMutation.cs
- api/Schema/Queries/NotificationQuery.cs
- client/src/components/molecules/NotificationPopOver/index.tsx
- client/src/components/organisms/Header/index.tsx
- client/src/graphql/mutations/notificationMutation.ts
- client/src/graphql/queries/NotificationQueries.ts
- client/src/hooks/useNotificationMutation.ts
- client/src/hooks/useNotificationQuery.ts
- client/src/utils/types/notificationTypes.ts
- https://framgiaph.backlog.com/view/HRIS-262
- Bugtask
- New notification(s)
- In the root directory, run ``` docker compose up ```
- By clicking the notification bell, it will reset the count of the notification.
- It will also set all the notifications ```isRead``` to ``` true ``` in the notifications table
- If the notification was received while you're on the notifications page, the notification will be set to isRead true automatically
https://github.com/framgia/sph-hris/assets/109492180/0d691f0f-1615-4dd7-bdcc-618ffbe9f6ef
> HRIS-262 [FE/BE] Fix notification counter not updating the 'isRead' property when clicking the bell icon

- api/Services/EmployeeService.cs
https://framgiaph.backlog.com/view/HRIS-265
- ESL positionId : `5`
- (docker) run `docker compose up db api -d`
- (local api) run `dotnet run`
- run the following mutation
```
mutation ($request: AddNewEmployeeRequestInput!) {
addNewEmployee(request: $request)
}
{
"request": {
"email": "test@test.com",
"positionId" : 5,
"roleId" : 3,
"firstName": "Juan",
"middleName": "middle",
"lastName": "Manuel"
}
}
```
- If the position of the new employee is not ESL, it should only create new user
- If the position of the new employee is ESL, it should also create new schedule data in tables `EmployeeSchedules` and `WorkingDayTimes`
- If the position of the new employee is ESL, its `scheduleId` should be the `Id` of newly created schedule …
> HRIS-265 [BE] Update 'Add Employee' Feature to Enable Employee Schedule Creation

- client/src/pages/api/auth/[...nextauth].ts
- https://framgiaph.backlog.com/view/HRIS-267
- BUGFIX
- In the root directory ``` docker compose up db api client -d ```
- When the login button is click, it should direct afterwards to the selection of email(s)
https://github.com/framgia/sph-hris/assets/109492180/4937a400-f2ff-434c-8bd3-6cea60e186e7
> HRIS-267 [Bugfix] Fix user login where it skips the selection of email if there's only one email currently saved

- client/src/hooks/useTimeInMutation.ts
- client/src/hooks/useTimeOutMutation.ts
https://framgiaph.backlog.com/view/HRIS-268
- Improvement task
- In the root directory, run ``` docker compose up db api client -d ```
- Time In time should be reflected real time right after saving the clock in
- Time Out time should be reflected real time right after saving the clock out
https://github.com/framgia/sph-hris/assets/109492180/4d3392c2-cc28-4d06-80b1-6b728f0d5a02
> HRIS-268 [BE/FE] Automatically update the 'Time In' and 'Time Out' columns in My DTR Page upon user clock-in and clock-out

- api/Context/HrisContext.cs
- api/DTOs/TimeEntryDTO.cs
- api/Entities/TimeEntry.cs
- api/Entities/WorkingDayTime.cs
- api/Enums/WorkStatusEnum.cs
- api/Migrations/20230523074842_AddBreakTime.Designer.cs
- api/Migrations/20230523074842_AddBreakTime.cs
- api/Program.cs
- api/Seeders/DatabaseSeeder.cs
- api/Services/EmployeeService.cs
- api/Services/TimeInService.cs
- api/Services/TimeOutService.cs
- api/Services/TimeSheetService.cs
- client/src/components/atoms/WorkStatusChip/index.tsx
- client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx
- client/src/components/molecules/MyOvertimeTable/columns.tsx
- client/src/components/molecules/OvertimeManagementTable/columns.tsx
- client/src/components/organisms/Header/index.tsx
- client/src/utils/constants/work-status.ts
- client/src/utils/myDailyTimeHelpers.ts
https://framgiaph.backlog.com/view/HRIS-266
- You may check this PR with FE, since it's already fully integrated
- This PR also includes FE bugfix for `WorkHours`
- Simulated scheduler is not included in the code. Only for recording purposes
- Comments from sir Jem
- https://sun-philippine.slack.com/archives/C04FYBQ4LRZ/p1684290515453809 (Undertime)
- https://sun-philippine.slack.com/archives/C04FYBQ4LRZ/p1684377030885819 (WorkHours)
- https://sun-philippine.slack.com/archives/C04FYBQ4LRZ/p1684389881456529 (Timer)
- https://sun-philippine.slack.com/archives/C04FYBQ4LRZ/p1684463338119189 (Default Absent Status)
- https://sun-philippine.slack.com/archives/C04FYBQ4LRZ/p1684735322961049 (Weekend as Absent)
- go to `My Daily Time …
> HRIS-266 [BE] Modify DTR Management Computation on both Summary and Overview table

- client/src/components/molecules/AddNewOvertimeModal/index.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/ChangeShiftRequestModal.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
https://framgiaph.backlog.com/view/HRIS-273
- Also fixed computation of Overtime in MyDTR table
- go to `My Daily Time Record` page
- The leaders in the dropdown of Add New Overtime Modal and Change Shift Request Modal should be users with positions `Admin`, `Web Developer - Trainer`, `Web Developer - Team Leader`
- The page should also not break when opening these two modals
https://github.com/framgia/sph-hris/assets/111718037/f00640ef-242f-42c3-977e-0e9302683762
> HRIS-273 [Bugfix]  Fix the Project Leader Dropdown in the File Overtime Request Modal and Non-ESL Change Shift Request Modal

- client/src/components/atoms/CellTimeValue/index.tsx
- client/src/components/molecules/DTRManagementTable/columns.tsx
- client/src/components/molecules/DTRSummaryTable/columns.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
- https://framgiaph.backlog.com/view/HRIS-270
- Improvement task on
- My Daily Time Record
- DTR Management & Summary
- In the root directory, run ``` docker compose up db api client -d  ```
- Show a tooltip showing the equivalent value, in hours, of late, undertime, and overtime values
https://github.com/framgia/sph-hris/assets/109492180/7d8ebf65-036b-4003-83c5-752cef0572e7
> HRIS-270 [BE/FE] Add an option in My DTR and DTR Management to display hours instead of minutes

- client/src/components/molecules/DTRManagementTable/columns.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
- client/src/components/molecules/MyOvertimeTable/columns.tsx
- client/src/components/molecules/OvertimeManagementTable/columns.tsx
- https://framgiaph.backlog.com/view/HRIS-270
- PR fix
- In the root directory, run ``` docker compose up db api client -d ```
- Column Approved Minutes on my overtime and overtime management page should now show a tooltip
- Removed tooltip for timeIn and timeOut columns
https://github.com/framgia/sph-hris/assets/109492180/35e046ff-aeaf-4901-aa4c-af8f54695c2c
> HRIS-270-01 [BE/FE] Fix: Added a tooltip on MyOvertime & OvertimeManagement page, and removed tooltip for TimeIn and TimeOut columns

- api/Enums/PositionEnum.cs
- api/Schema/Mutations/ChangeShiftMutation.cs
- api/Schema/Mutations/ESLChangeShiftMutation.cs
- api/Schema/Mutations/ESLOffsetMutation.cs
- api/Services/ApprovalService.cs
- api/Services/ChangeShiftService.cs
- api/Services/ESLChangeShiftService.cs
- api/Services/ESLOffsetService.cs
- api/Services/InterruptionService.cs
- api/Services/NotificationService.cs
- api/Services/OvertimeService.cs
- api/Services/ProjectService.cs
- api/Services/TimeSheetService.cs
- api/Utils/Validation.cs
- api/Utils/Validation/ApprovalServiceInputValidation.cs
https://framgiaph.backlog.com/view/HRIS-277
- It's ideal to have access to three accounts to check for the notifications. One normal user, one leader ( `positionId` = 3, 6 or 7) and one manager (`roleId` = 1)
- `ESL Change Shift` and `ESL Offset` are only for ESL Users (`positionId` = 5)
- To make Leave/Undertime request, go to `My Leaves` page
- To make Overtime request, go to `My Overtime` page
- To make Change Shift request, go to `My Daily Time Record` page
- To make ESL Change Shift and Offset request, go to `My Daily Time Record` page
- Approve requests as Leader/Manager in `Notifications` page
- The name of requesting/approving/disapproving user should be displayed correctly in notifications. …
> HRIS-277 [BE/FE] Display the user's name who have approved or disapproved the filed requests

- client/src/components/molecules/UserTimeZone/index.tsx
- client/src/components/organisms/Header/index.tsx
- client/src/components/organisms/TimeInDrawer/index.tsx
- client/src/components/organisms/TimeOutDrawer/index.tsx
- client/src/utils/constants/sidebarMenu.ts
- client/src/utils/styles/globals.css
[Backlog Link
](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-275)
Do `npm run build` and then `npm start` to enter production mode. Check sidebar.
Try to time in during restday on your schedule.
1. When a user tries to login during his/her restday on schedule, the user will receive a confirmation modal if the user wants to proceed to time in during a rest day.
- Login with a user that has an assigned `EmployeeSchedules` and make sure `EmployeeSchedules` has no corresponding `WorkingDayTimes`  which indicates that the user is currently  in restday
2. The user will not receive a confirmation modal if it is not his restday.
- Login with a user that has an assigned `EmployeeSchedules` and make sure `EmployeeSchedules` has a corresponding `WorkingDayTimes`  which indicates …
> HRIS-275 [BE/FE] Add a confirmation modal when a user attempts to clock in during rest day.

- api/Schema/Mutations/TimeOutMutation.cs
- api/Services/TimeInService.cs
- api/Services/TimeOutService.cs
- client/src/components/organisms/Header/index.tsx
- client/src/utils/shared/serverTime.ts
https://framgiaph.backlog.com/view/HRIS-281
- The bug occurs when user is clocked in past the their scheduled work time and then clocked out
- To test timezone difference with the server it is important to run BE in docker
- Clock In / Clock Out
- User should be able to clock out normally regardless of when the last clock in
- When clocking in or clocking out, the time registered should be the server time and not the user's machine time
- The timer in FE shoud be consistent with the server time
https://github.com/framgia/sph-hris/assets/111718037/5688f7b7-16e3-426f-a47d-ecb2cd24f5ee
https://github.com/framgia/sph-hris/assets/111718037/d46e6225-407e-48c6-a000-df992cafb735
> HRIS-281 [BE] Resolve the issue preventing users from clocking in or out in the Clock-in and Clock-out functionality

- client/src/components/organisms/Header/index.tsx
- client/src/utils/shared/serverTime.ts
https://framgiaph.backlog.com/view/HRIS-281
- Revision PR from #234 
- open console in FE
- There should be no more warning in the console pf FE
> HRIS-281-1 [BE] Fix deprecated warning in timer

- api/DTOs/TimeEntryDTO.cs
- client/src/components/molecules/MyDailyTimeRecordTable/AddNewOffsetModal.tsx
- client/src/graphql/queries/unusedESLOffsets.ts
- client/src/hooks/useUnusedESLOffset.ts
https://framgiaph.backlog.com/view/HRIS-283
- (docker) run `docker compose up api db client --build -d`
- As ESL user, when filing Change Shift, all unused and approved ESLoffsets should be displayed as option in the dropdown
- In any DTR page, only approved leave will be displayed as status
https://github.com/framgia/sph-hris/assets/111718037/dd0f4b45-4761-4378-98b3-016a2982eec2
> HRIS-283 [FE] Fix File Offset Functionality

- client/src/graphql/queries/leaveQuery.ts
- https://framgiaph.backlog.com/view/HRIS-285
- Bugtask on yearly summary heatmap and table
- In the client directory, run ``` npm run build  ``` and then ``` npm start ```
- Go to ``` http://localhost:3000/leave-management/yearly-summary ```
- It should reflect  the correct leaveName on the heatmap, and reflect the chipped value of status column on table
> HRIS-285 [FE] Fix 'undefined' value on to the tooltip when hovering on the heatmap data

- client/src/components/organisms/TimeInDrawer/index.tsx
- client/src/components/organisms/TimeOutDrawer/index.tsx
- client/src/components/organisms/WorkInterruptionDrawer/index.tsx
- client/src/hooks/useTimeInMutation.ts
- client/src/hooks/useTimeOutMutation.ts
- https://framgiaph.backlog.com/view/HRIS-288
- It insures that the clock will only run after the Time In mutate
- When User try to Time In/Out it will wait synchronously and shows loading in the button and after that it will perform an automatic Time Start/Stop to prevent unnecessary problem of the timer 
- Also Improve the Button loading style and the toast message with Paste Icon
[timer.webm](https://github.com/framgia/sph-hris/assets/108642414/716cca8a-aa8f-42d0-8d62-47e964ecbaa1)
> HRIS-288 [BE/FE]  Fix the user clock-in and clock-out functionality so that it reflects immediately after the mutation.

- api/DTOs/LeavesTableDTO.cs
- api/Services/LeaveService.cs
- client/src/components/atoms/WorkStatusChip/index.tsx
- client/src/components/molecules/LeaveManagementResultTable/MobileDisclose.tsx
- client/src/components/molecules/LeaveManagementResultTable/columns.tsx
- client/src/graphql/queries/leaveQuery.ts
- client/src/utils/constants/pathnames.ts
- client/src/utils/types/leaveTypes.ts
https://framgiaph.backlog.com/view/HRIS-287
- Improvement task for addition of columns
- In the client directory, run ``` npm run build ``` and then ``` npm start ```
-  Go to ``` http://localhost:3000/leave-management/yearly-summary ```
- The name column should only reflect on the Yearly summary page
https://github.com/framgia/sph-hris/assets/109492180/48c6be3f-cb81-4c3b-8139-813c2b6801ef
https://github.com/framgia/sph-hris/assets/109492180/63713215-b3c2-42b8-9cf4-5e0263bd72ee
> HRIS-287 [FE/BE] Add user's name column in the Yearly Leave Summary Page

- client/src/components/molecules/OvertimeManagementTable/columns.tsx
- https://framgiaph.backlog.com/view/HRIS-290
- Client request
- The `Name` in the Overtime Management Table is updated to `Requester` text
> HRIS-290 [FE] Change "Name" to "Requester" in the Overtime Management Page for HR Admin and Manager

- client/src/components/atoms/Buttons/ClearButton.tsx
- client/src/components/organisms/ViewDetailsDrawer/UploadFiles.tsx
- client/src/components/organisms/ViewDetailsDrawer/index.tsx
- client/src/components/templates/ScheduleManagementLayout/ScheduleList/ScheduleItem.tsx
- client/src/pages/schedule-management.tsx
- client/src/utils/types/employeeScheduleTypes.ts
- client/src/utils/types/formValues.ts
- client/src/utils/validation/index.ts
- https://framgiaph.backlog.com/view/HRIS-282
- Only UI changed the previous integration is almost the same 
- Go to the Schedule Management Page
- HR Role will now have an updated UI with validation to Apply To All Fields Functionality
- Previous functionality is still integrated 
- It also have Schedule Shift Dropdown functionality for predefined `Morning Shift` and `Afternoon Shift`
[schedule-management 2.webm](https://github.com/framgia/sph-hris/assets/108642414/54f8a1b0-fb46-43b0-a641-2b1aba9011d7)
> HRIS-282 [FE] Modify Schedule Management Page

- client/src/components/molecules/OvertimeManagementTable/columns.tsx
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-292)
run docker 
or
dotnet watch, and npm run dev
HR Admins and Managers except for Daisan can no longer edit a filed overtime.
Proof
[screen-capture.webm](https://github.com/framgia/sph-hris/assets/109579325/1318bc49-1925-492b-94c3-5e805845bc7f)
> HRIS-292 [FE] Hide Edit Modal Icon in the Overtime Management Page for HR Admin and Manager

- api/DTOs/LeaveDTO.cs
- api/DTOs/LeavesDTO.cs
- api/DTOs/LeavesTableDTO.cs
- api/Entities/LeaveNotification.cs
- api/Enums/SuccessMessageEnum.cs
- api/Requests/UpdateLeaveRequest.cs
- api/Schema/Mutations/LeaveMutation.cs
- api/Schema/Queries/LeaveQuery.cs
- api/Services/LeaveService.cs
- api/Utils/Validation.cs
- client/src/components/molecules/EditLeaveModal/EditTab.tsx
- client/src/components/molecules/EditLeaveModal/index.tsx
- client/src/components/molecules/LeaveManagementResultTable/Table.tsx
- client/src/components/molecules/LeaveManagementResultTable/columns.tsx
- client/src/components/molecules/LeaveManagementResultTable/index.tsx
- client/src/graphql/mutations/leaveMutation.ts
- client/src/graphql/queries/leaveQuery.ts
- client/src/hooks/useLeave.ts
- client/src/utils/types/leaveTypes.ts
- https://framgiaph.backlog.com/view/HRIS-276
- A user must have an existing leave that is on pending status
- In the client directory, run ``` npm run build ``` and then ``` npm start ```
- Go to ``` http://localhost:3000/my-leaves?year=2023 ```
- My leaves table should reflect a new column for actions
- Upon clicking on Edit action, it should display the correct details of the leave request
- Upon clicking save, it should close the modal and show a toast
- All of the notifications for the recipients should reflect again asking for approval
https://github.com/framgia/sph-hris/assets/109492180/711260dc-856f-4615-9d8e-2dee212bf3b8
https://github.com/framgia/sph-hris/assets/109492180/8174e344-258d-48bf-8fca-17c4355c1401 …
> HRIS-276 [BE/FE] Add functionality to enable users to edit their filed leave

- api/Services/ApprovalService.cs
- https://framgiaph.backlog.com/view/HRIS-293
- Bug task only on approval/disapproval service for multiple managers
- There must be at least two ```manager``` position in the ```Users``` table to try and test 
- Backend
- In the ```api``` directory run ``` dotnet run ```
- To check the functionality, go to ``` http://localhost:3000/overtime-management ``` where user role should be ``` manager ``` and user position is ``` manager ``` or ``` assistant manager ```
- It should alter the ```isManagerApproved``` column in the ```Overtimes``` table
https://github.com/framgia/sph-hris/assets/109492180/3e7e9545-4f47-442c-a343-03a2724ffe7a
> HRIS-293 [BE/FE] Overtime Management page should support multiple managers

- client/src/components/molecules/LeaveManagementResultTable/columns.tsx
- client/src/utils/constants/pathnames.ts
- https://framgiaph.backlog.com/view/HRIS-276
- Fix pr
- In the ```api``` directory, run ```dotnet run```
- Go to ```http://localhost:3000/my-leaves?year=2023```
- ```Actions``` columns should be hidden on other leaves table
https://github.com/framgia/sph-hris/assets/109492180/75a5943f-1085-474b-86bd-94365bde03c1
> HRIS-276-01 [BE/FE] Fix: Actions should only appear on my-leaves page

- client/src/utils/constants/sidebarMenu.ts
- https://framgiaph.backlog.com/view/HRIS-295
- None
- In the ```api``` directory, run ```dotnet run```
- Employee management and My schedule page should be hidden on production mode
> HRIS-295 [FE] Hide Employee Management and My Schedule Page in Production Mode

- client/src/components/molecules/FiledOffsetModal/MobileDisclose.tsx
- client/src/components/molecules/FiledOffsetModal/ShowRemarksModal.tsx
- client/src/components/molecules/FiledOffsetModal/columns.tsx
- client/src/components/molecules/InterruptionTimeEntriesModal/ShowRemarksModal.tsx
- client/src/components/molecules/InterruptionTimeEntriesModal/columns.tsx
- client/src/components/molecules/LeaveManagementResultTable/columns.tsx
- client/src/components/molecules/ListOfLeaveTable/MobileDisclose.tsx
- client/src/components/molecules/ListOfLeaveTable/ShowReasonModal.tsx
- client/src/components/molecules/ListOfLeaveTable/columns.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/ViewFiledChangeShiftModal/index.tsx
- client/src/components/molecules/MyFiledScheduleTable/MobileDisclose.tsx
- client/src/components/molecules/MyFiledScheduleTable/columns.tsx
- client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx
- client/src/components/molecules/MyOvertimeTable/ShowRemarksModal.tsx
- client/src/components/molecules/MyOvertimeTable/columns.tsx
- client/src/components/molecules/NotificationList/NotificationItem.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/index.tsx
- client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx
- client/src/components/molecules/OvertimeManagementTable/ShowRemarksModal.tsx
- client/src/components/molecules/OvertimeManagementTable/columns.tsx
- https://framgiaph.backlog.com/view/HRIS-294
- Used `react-icons` from the changes 
- The `Eye` icon are now replaced into a `Notes` icon from `react-icons`
[change-eye-into-notes.webm](https://github.com/framgia/sph-hris/assets/108642414/2efaa1a0-a7ff-4edf-8302-a4ff6d9cac31)
> HRIS-294 [FE] Change eye icon to note icon in all of the pages

- client/src/pages/dtr-management.tsx
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-289)
Run front end `npm run dev`  and go to dtr management page
For this task make sure your backend is down or not running to test the error catcher.
It should notify the users in DTR Management that there is something wrong trying to fetch the data from the backend.
Proof
[screen-capture (2).webm](https://github.com/framgia/sph-hris/assets/109579325/5b002708-1bcc-4ac3-8da0-8f873f587b5f)
> HRIS-289 [FE] Handling Fetching Error on DTR Management Page

- client/src/components/atoms/ProjectChip/index.tsx
- client/src/components/molecules/ListOfLeaveTable/MobileDisclose.tsx
- client/src/components/molecules/ListOfLeaveTable/columns.tsx
- client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx
- client/src/components/molecules/MyOvertimeTable/columns.tsx
- client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx
- client/src/components/molecules/OvertimeManagementTable/columns.tsx
- client/src/pages/leave-management/list-of-leave.tsx
- client/src/utils/createLeaveHelpers.ts
- client/src/utils/interfaces/index.tsx
- https://framgiaph.backlog.com/view/HRIS-296
- This is a client request for improvements
- goto to all tables that has project columns to view the cheap
- Each table that has project columns are now refactored into a Project Cheap with amber color design
[test-tse.webm](https://github.com/framgia/sph-hris/assets/108642414/adeafbb3-0ca7-42d2-83ea-f6440b4d6c00)
> HRIS-296 [FE] Convert Project column values from all application tables into tags instead of using dropdown menus

- client/src/components/molecules/OvertimeManagementTable/ApproveConfirmationModal.tsx
- client/src/components/molecules/OvertimeManagementTable/DisapproveConfirmationModal.tsx
- https://framgiaph.backlog.com/view/HRIS-297
- None
- In the ```api``` directory, run ```dotnet run```
- If there's a broken image link, the default image will take over on approve/disapprove modal
https://github.com/framgia/sph-hris/assets/109492180/89d79984-9060-458d-b455-7587bf516fcf
> HRIS-297 [FE] Add Error Image handier on the Approve and Disspprove modal

- client/src/components/molecules/LeaveManagementResultTable/columns.tsx
- https://framgiaph.backlog.com/view/HRIS-272
- None
- In the ```api``` directory, run ```dotnet run```
- Aligned icons for Edit and Cancel
> HRIS-272-01 [BE/FE] Fix: aligned the icons for Edit and Cancel

- client/src/components/molecules/SummaryFilterDropdown/index.tsx
- client/src/components/templates/LeaveManagementLayout/index.tsx
- client/src/pages/leave-management/leave-summary.tsx
- client/src/pages/leave-management/yearly-summary.tsx
- client/src/pages/my-leaves.tsx
- https://framgiaph.backlog.com/view/HRIS-299
- Figma design for My Leaves Page
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?type=design&node-id=5361-28462&t=QBn5wJsfjM3jzELS-4
- Figma design for Leave Summary Tab Page
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?type=design&node-id=5344-28221&t=QBn5wJsfjM3jzELS-4
- Figma design for Yearly Summary Tab Page
- https://www.figma.com/file/w3lR4Elj1q5yZgK3Xw0eIx/HRIS-Wireframe?type=design&node-id=5361-29609&t=QBn5wJsfjM3jzELS-4
- goto `My Leave Page, Leave Summary and Yearly Summary` pages
- The My leaves, Leave Summary and Yearly Summary Dropdown Filter are removed and replaced to newly requested design …
> HRIS-299 [FE] Enhance Leave Management and My Leave Sections to Present Filter Options within the Content

- client/src/components/atoms/Logo/index.tsx
- client/src/components/atoms/ProjectChip/index.tsx
- client/src/components/molecules/DTRManagementTable/DesktopTable.tsx
- client/src/components/molecules/DTRManagementTable/index.tsx
- client/src/components/molecules/DTRSummaryTable/DesktopTable.tsx
- client/src/components/molecules/DTRSummaryTable/columns.tsx
- client/src/components/molecules/DTRSummaryTable/index.tsx
- client/src/components/molecules/EmployeeManagementTable/DesktopTable.tsx
- client/src/components/molecules/EmployeeManagementTable/MobileDisclose.tsx
- client/src/components/molecules/EmployeeManagementTable/columns.tsx
- client/src/components/molecules/EmployeeManagementTable/index.tsx
- client/src/components/molecules/ListOfLeaveTable/DesktopTable.tsx
- client/src/components/molecules/ListOfLeaveTable/index.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/DesktopTable.tsx
- client/src/components/molecules/MyDailyTimeRecordTable/index.tsx
- client/src/components/molecules/MyOvertimeTable/DesktopTable.tsx
- client/src/components/molecules/MyOvertimeTable/columns.tsx
- client/src/components/molecules/MyOvertimeTable/index.tsx
- client/src/components/molecules/OvertimeManagementTable/DesktopTable.tsx
- client/src/components/molecules/OvertimeManagementTable/columns.tsx
- client/src/components/molecules/OvertimeManagementTable/index.tsx
- client/src/components/molecules/SummaryFilterDropdown/index.tsx
- client/src/pages/dtr-management.tsx
- client/src/pages/employee-management.tsx
- client/src/pages/my-daily-time-record.tsx
- https://framgiaph.backlog.com/view/HRIS-300
- Requested by the client
- Each page's table layout fills out the entire space of the content and sets a minimum width to display a horizontal scroll, preventing the content from being stretched and broken
- List of Pages of table changed:
- My Daily Time Record
- My Overtime
- Leave management -> List of Leave Tab Page
- DTR Management 
- Overtime Management 
[record for table improvements.webm](https://github.com/framgia/sph-hris/assets/108642414/3995cc71-9206-49aa-868e-4520bfb030ee)
> HRIS-300 [FE] Optimize Table Layouts Across All Pages

- api/Services/TimeOutService.cs
https://framgiaph.backlog.com/view/HRIS-309
- (docker) run `docker compose up db api client -d`
- The value of Worked Hours is now computed in the backend and not based on the frontend time
https://github.com/framgia/sph-hris/assets/111718037/4bcaa711-d406-4d83-b17a-1eae8b5cc377
> HRIS-309 [BE] Fix inaccurate display of worked hours in My DTR and DTR Management Pages

- api/Enums/MiddlewareErrorMessageEnum.cs
- api/Middlewares/Attributes/LeaderUserAttribute.cs
- api/Middlewares/AuthorizeUser.cs
- api/Middlewares/LeaderUser.cs
- api/NotificationDataClasses/OvertimeData.cs
- api/Requests/CreateBulkOvertimeRequest.cs
- api/Schema/Mutations/OvertimeMutation.cs
- api/Services/NotificationService.cs
- api/Services/OvertimeService.cs
- api/Utils/Validation/OvertimeServiceInputValidation.cs
https://framgiaph.backlog.com/view/HRIS-301
- (docker) run `docker compose up db api -d`
- to create bulk request, run the following mutation
```
mutation ($request: CreateBulkOvertimeRequestInput!) {
createBulkOvertime(request: $request){
id
}
}
{
"request": {
"managerId": 70,
"requestedMinutes": 69,
"remarks": "testing",
"employeeIds": [4,5],
"date": "2023-06-13",
"projectId":1
}
}
```
- to monitor notification, run the following subscription
```
subscription {
overtimeCreated(id: 70) {
id
type
data
readAt
isRead
}
}
```
- Only leaders (positionId = 3, 6, or 7) can create bulk overtime requests
- Overtimes created should be pre-approved by leader
- There should be one notification for every project member included in the request
- Notification …
> HRIS-301 [BE] Implement Bulk Overtime Request for Team Leader

- api/Enums/LeaveTypeEnum.cs
- api/Schema/Queries/LeaveQuery.cs
- api/Services/LeaveService.cs
- client/src/components/molecules/SummaryFilterDropdown/index.tsx
- client/src/graphql/queries/leaveQuery.ts
- client/src/hooks/useLeave.ts
- client/src/pages/leave-management/leave-summary.tsx
- client/src/pages/leave-management/yearly-summary.tsx
- client/src/pages/my-leaves.tsx
- client/src/utils/constants/leaveOptions.ts
- https://framgiaph.backlog.com/view/HRIS-308
- This is project client request
- The Filter functionality is Serverside
- Default `LeaveTypeId` set to `0` which is `All`
- The `leaveTypeId` are based in this image
- The `leaveTypeId` of 7 is equal to `Pending` Status
- go to `My Leaves`, `Leave Summary` and `Yearly Summary` Page to test the filter
- The `My Leaves`, `Leave Management` Pages are now have a Leave Filter Functionality
[leave filter record.webm](https://github.com/framgia/sph-hris/assets/108642414/14bf5707-e1bb-4984-9c64-cd6ca2e67a43)
> HRIS-308 [BE/FE] Add filtering functionality in the my leaves and leave management pages

- api/Services/SigninService.cs
- client/src/utils/shared/client.ts
https://framgiaph.backlog.com/view/HRIS-312
- User should be able to login in the dev server
https://github.com/framgia/sph-hris/assets/111718037/970d0c35-cf16-4e18-a602-d6edc1d78cc0
> HRIS-312 [FE/BE] Fix user cannot login due to the modification of the authentication part of the application

- client/src/components/molecules/LeaveCellDetailsModal/ShowReasonModal.tsx
- client/src/components/molecules/LeaveCellDetailsModal/Table.tsx
- client/src/components/molecules/LeaveCellDetailsModal/columns.tsx
- client/src/components/molecules/LeaveCellDetailsModal/index.tsx
- client/src/components/molecules/LeaveManagementResultTable/index.tsx
- client/src/components/molecules/SummaryFilterDropdown/index.tsx
- client/src/components/templates/ModalTemplate/index.tsx
- client/src/pages/leave-management/leave-summary.tsx
- client/src/pages/leave-management/yearly-summary.tsx
- client/src/pages/my-leaves.tsx
- client/src/utils/constants/dummyMyLeaveCellDetails.ts
- client/src/utils/createLeaveHelpers.ts
- client/src/utils/generateData.ts
- client/src/utils/types/leaveTypes.ts
- https://framgiaph.backlog.com/view/HRIS-311
- Client Request
- For the meantime, any cells will be clickable even if the cell is empty and I will experiment how to prevent it in the near future
- goto `my-leaves`, `/leave-management/leave-summary` and `/leave-management/yearly-summary`
- User will able to click the cell in the heatmap and will show the markup design for Leave Modal Details
[leave heatmap cell.webm](https://github.com/framgia/sph-hris/assets/108642414/23906f38-815e-4022-b142-f54740951d93)
> HRIS-311 [Markup] Create Leaves Modal when user a clicks a cell on the Heatmap

- api/DTOs/OvertimeDTO.cs
- client/src/components/molecules/DTRManagementTable/columns.tsx
https://framgiaph.backlog.com/view/HRIS-313
- Also added fix for query in Overtime Management page
- (docker) run `docker compose up db api client -d`
- go to DTR Management page
- The global filter for DTR Management page should be working now
https://github.com/framgia/sph-hris/assets/111718037/72f49e59-88bc-47e4-a2e2-47aff1268e63
> HRIS-313 [FE] Fix table search functionality in DTR Management Page

- client/src/pages/_app.tsx
- https://framgiaph.backlog.com/view/HRIS-318
- Client Request
- Style Guide: https://react-hot-toast.com/docs/styling
- Any toast message are re-aligned to be at the bottom of the navbar
[toast notification message.webm](https://github.com/framgia/sph-hris/assets/108642414/67335967-91dc-48c9-bbda-327bf0a39b5c)
> HRIS-318 [FE] Re-align the toast notification to be at the bottom of the navbar

- client/src/components/organisms/TimeInDrawer/index.tsx
- client/src/components/organisms/ViewDetailsDrawer/index.tsx
- https://framgiaph.backlog.com/view/HRIS-319
- In production it seems that the Time In and Time Out data is actually meet the formatted time. I only reformatted the timeHour using Momentjs
- goto DTR pages
- The displayed time in Drawer Details are now formatted using MomentJS functionality
[reformattedTimeHour.webm](https://github.com/framgia/sph-hris/assets/108642414/b7e3fe27-ad8f-41f8-9c46-29a4ca3311c7)
> HRIS-319 [Bugfix] Fix Time Displayed format in the Drawer where it displays incorrect time

- api/Services/TimeOutService.cs
https://framgiaph.backlog.com/view/HRIS-320
- (docker) run `docker compose up db api client -d`
- There should be Time In from previous day
- When user clocked-out the next day, the worked hours value should be computed correctly
https://github.com/framgia/sph-hris/assets/111718037/3ccefd52-84cc-4c76-be28-5f86a536661e
> HRIS-320 [Bugfix] Inaccurate value  computation of Work Hours in My DTR and DTR Management

- api/DTOs/LeavesDTO.cs
- client/src/components/molecules/AddNewLeaveModal/LeaveTab.tsx
- client/src/components/molecules/AddNewLeaveModal/UndertimeTab.tsx
- client/src/components/molecules/EditLeaveModal/EditTab.tsx
- client/src/components/molecules/LeaveCellDetailsModal/index.tsx
- client/src/components/molecules/LeaveManagementResultTable/columns.tsx
- client/src/hooks/useLeave.ts
- client/src/utils/createLeaveHelpers.ts
- https://framgiaph.backlog.com/view/HRIS-321
- Not yet fixed the invalidate queries for edit leave
- Any User should be able to view the data when clicking the heatmap cell
- Data should be ascending order
[fix.webm](https://github.com/framgia/sph-hris/assets/108642414/673358e9-067d-495a-87b4-7db08a00c663)
> HRIS-321 [Bugfix] Fix displayed filed leaves of the clicked cell in the heat map data

- api/Enums/SuccessMessageEnum.cs
- api/Requests/CreateSummaryRequest.cs
- api/Schema/Mutations/OvertimeMutation.cs
- api/Services/NotificationService.cs
- api/Utils/Validation.cs
- client/src/components/molecules/MyOvertimeTable/OptionDropdown.tsx
- client/src/components/molecules/NotificationList/NotificationItem.tsx
- client/src/components/molecules/OvertimeManagementTable/SummaryConfirmationModal.tsx
- client/src/components/organisms/Header/index.tsx
- client/src/graphql/mutations/overtimeMutation.ts
- client/src/graphql/subscriptions/leaveSubscription.ts
- client/src/hooks/useOvertime.ts
- client/src/pages/overtime-management.tsx
- client/src/utils/types/overtimeTypes.ts
- https://framgiaph.backlog.com/view/HRIS-316
- HR Admin user
- (docker) run ``` docker compose up api db client -d```
- Go to ```http://localhost:3000/overtime-management```
- Change the filter days time sheet range
- Choosing a range should filter the list of overtime base on date filed
- A button for ```send summary``` should appear
- Hitting ``` send summary ``` should disable the button
https://github.com/framgia/sph-hris/assets/109492180/c5968f68-58d4-45bf-b1ef-f1e93945dcb0
> HRIS-316 [BE/FE] Integrate new filter for summarized overtime in HR Admin page

- client/src/components/molecules/AddNewLeaveModal/UndertimeTab.tsx
- client/src/components/molecules/InterruptionTimeEntriesModal/columns.tsx
- client/src/components/molecules/LeaveCellDetailsModal/index.tsx
- client/src/components/molecules/LeaveManagementResultTable/columns.tsx
- client/src/components/templates/ScheduleManagementLayout/ScheduleList/ScheduleItem.tsx
- client/src/hooks/useLeave.ts
- https://framgiaph.backlog.com/view/HRIS-323
- Improvements on Confirm Alert Modal Button
- It should now have a simple text 'Canceling...'/'Deleting...' when clicking "Yes" on the alert modal
[222222.webm](https://github.com/framgia/sph-hris/assets/108642414/37a982d0-e447-4a2b-88b7-8f02e784dd74)
> [FE] Add Canceling Text Indicator in Confirm Alert Modal

- client/src/components/molecules/EditUndertimeModal/EditTab.tsx
- client/src/components/molecules/EditUndertimeModal/index.tsx
- client/src/components/molecules/LeaveManagementResultTable/columns.tsx
- https://framgiaph.backlog.com/view/HRIS-322
- Existing undertime request
- Running BE and FE
- Go to ``` http://localhost:3000/my-leaves?year=2023&leave=0 ```
- Edit a leave request to test the Reset button
- Edit an undertime request to test the save and reset button
- It should allow the user to reset the data on the leave and undertime form
- It should allow the user to edit undertime requests
https://github.com/framgia/sph-hris/assets/109492180/e4f064b0-6655-42fc-a1d0-de9acd488781
> HRIS-322 [FE] Add Edit undertime form for undertime requests

- client/src/components/atoms/RequestStatusChip/index.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/ChangeShiftDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/ChangeShiftResolved.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/ESLChangeShiftDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/LeaveDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/LeaveResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/OffsetDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/OffsetResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/OffsetScheduleDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/OvertimeDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/OvertimeResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/ResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/UndertimeDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/UndertimeResolvedDetails.tsx
- client/src/components/molecules/NotificationList/ViewDetailsModal/index.tsx
- client/src/components/templates/ModalTemplate/ModalHeader.tsx
- client/src/components/templates/ModalTemplate/index.tsx
- client/src/utils/constants/requestStatus.ts
- https://framgiaph.backlog.com/view/HRIS-325
- Notification Details Modal Improvement to emphasize the status of request
- go to notication dropdown menu and select notification data
- The Notification Details Modal should now feature a modified user interface (UI) that incorporates shadows and borders based on the status of a request
- Modified Status details with Chip Component
[noti-noti.webm](https://github.com/framgia/sph-hris/assets/108642414/08cc7b2e-81fa-4157-85d1-1ff98aa721ae)
> HRIS-325 [FE] Modify design on Notification Details Modal

- api/.env.example
- api/.gitignore
- api/Program.cs
- api/api.csproj
- https://framgiaph.backlog.com/view/HRIS-317
- Conditional string can now be removed from here after we update the .env file in dev server
- To use environment variables in the services, add these configurations
- Sample usage
- In the root directory, run ``` docker compose up api db client -d ```
- In the root directory, run ``` touch .env ```
- Access the ``` .env ``` file and paste this sample content
```
DB_HOST="localhost\\db-1,1433"
DB_PASSWORD="P@ssw0rd"
DB_NAME="hris"
DB_USER="sa"
```
- It should let the services access the variables inside .env
- ```.env``` file
- Usage
> HRIS-317 [BE] Add .env file in the API and update the env.example

- api/Middlewares/AuthorizeUser.cs
- https://framgiaph.backlog.com/view/HRIS-331
- BE implementation only
- Go to ``` http://localhost:5257/graphql/ ```
- Run this query:
```
query {
userById {
employeeSchedule {
workingDayTimes {
id
day
from
to
breakFrom
breakTo
}
}
}
}
```
- It should return a list of schedule
> HRIS-331 [BE]  Implement fetching of employee schedule for a specific user

- api/DTOs/EmployeeScheduleDTO.cs
- api/Requests/WorkingDayTimesRequest.cs
- api/Services/EmployeeScheduleService.cs
- api/Utils/Validation.cs
- client/src/components/templates/ScheduleManagementLayout/ScheduleList/ScheduleItem.tsx
- client/src/graphql/mutations/employeeScheduleMutation.ts
- client/src/graphql/queries/employeeSchedule.ts
- client/src/pages/schedule-management.tsx
- client/src/utils/constants/shiftSchedule.ts
- client/src/utils/types/employeeScheduleTypes.ts
- https://framgiaph.backlog.com/view/HRIS-329
- Integration with BE
- Only HR can access the page
- It should now have and update and save for the column of Break From and Break To
- The Schedule Shift dropdown are now integrated
[integration.webm](https://github.com/framgia/sph-hris/assets/108642414/f0600a4a-e4b9-4352-a7f3-c730dfa4f71d)
> HRIS-329 [FE/BE] Update data fetched from employee schedules to cater BreakFrom and BreakTo values

- client/src/components/templates/ScheduleManagementLayout/ScheduleList/ScheduleItem.tsx
- client/src/pages/schedule-management.tsx
- https://framgiaph.backlog.com/view/HRIS-329
- Revision task
- go to the `schedule-management` page
- It should fix the previous bug in initial load with data to reset all data
- Also hide schedule name text and hide schedule shift dropdown navigating existing schedule
[fix.webm](https://github.com/framgia/sph-hris/assets/108642414/5996671d-2538-441c-bb83-396bfec037dc)
> HRIS-329-01 [FE] Fix initial load and hide schedule shift dropdown

- api/Schema/Queries/EmployeeScheduleQuery.cs
- api/Services/EmployeeScheduleService.cs
- https://framgiaph.backlog.com/view/HRIS-335
- BE only
- In the api directory, run ``` dotnet watch ```
- Go to ``` http://localhost:5257/graphql/ ```
- Run this mutation:
```
query($userId: Int!) {
employeeChangeScheduleRequest(userId: $userId) {
id
data
isManagerApproved
isLeaderApproved
createdAt
}
}
{
"userId": 57
}
```
- It should fetch all the filed request for that user
> HRIS-335 [BE] Implement fetching of filed schedules on a specific user

- api_v2/src/app.module.ts
- api_v2/src/decorators/position.decorator.ts
- api_v2/src/guards/position.guard.ts
- api_v2/src/sign-in/sign-in.service.ts
Backlog Link
https://framgiaph.backlog.com/view/HRIS-371
I used create workInterruption to test the position guard
Add UseGuards(PositionGuard)
Add Position(PositionEnum.<Position Key from PositionEnum>) 
Use sign in mutation of api_v2 to get the auth token
A transaction should not succeed when transaction is for a specific Position that is not the position of the user
Successful transaction for position Web Developer
Unsuccessful transaction for position Web Developer
> HRIS-371 Position Middleware/Guards

- api_v2/src/utilities/date.util.ts
- api_v2/src/work-interruption/work-interruption.resolver.ts
- api_v2/src/work-interruption/work-interruption.service.ts
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-381&milestone=316260)
Optional
- Please create a time entry first if not yet created and use its Id on the variables
-You can access the graphql playground enpoint at http://localhost:3001/graphql/
-To run the update mutation, use the following below:
`mutation($interruption: UpdateInterruptionRequestInput!){
updateWorkInterruption(interruption:$interruption)
}`
- Use this as your variable respectively:
`{
"interruption": {
"id": 2,
"otherReason":"Update NEW REASON",
"remarks":"Update remarks",
"timeIn":"09:30:00",
"timeOut":"18:30:00",
"workInterruptionTypeId": 3
}
}`
- Create a time entry first if not yet created.
-run `docker compose up db`
-run `npm run dev or run start`
-Same Output with the ASP.net and …
> [HRIS-381] [BE] My Daily Time Record > Index > View Work Interruptions > Edit Work Interruption

- api_v2/src/work-interruption/work-interruption.resolver.ts
- api_v2/src/work-interruption/work-interruption.service.ts
[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-407&milestone=316260)
- Please create a time entry first if not yet created and use its Id on the variables
- To run delete mutation, use the following below:
`mutation($id:Int!){
deleteWorkInterruption(id:$id)
}   `
`{
"id":2
}`
- `docker compose up db`
- `npm start` or `npm run dev`
It should be the same output with the GraphQL of ASP.net
NestJS output in GraphQL:
ASP.net output in GraphQL:
> [HRIS-407] [BE] DTR Management > Index > View Work Interruptions > Delete Work Interruption

- api_v2/src/app.module.ts
- api_v2/src/graphql/graphql.ts
- api_v2/src/graphql/schema.gql
- api_v2/src/overtime/overtime.module.ts
- api_v2/src/overtime/overtime.resolver.spec.ts
- api_v2/src/overtime/overtime.resolver.ts
- api_v2/src/overtime/overtime.service.spec.ts
- api_v2/src/overtime/overtime.service.ts
https://framgiaph.backlog.com/view/HRIS-409
- The supervisor and projects (null) on Query by ID is not working yet because it is dependent on another task which has not yet been implemented. Removing the projects and supervisor on the query will make the query work
- Will update this PR once done
Commands to run:
-[x] npm run dev
It should Query the overtime of all users and user by ID
Query all user Overtime
Query Overtime for user by ID
> HRIS-409 [BE] Overtime Management > Index

- api_v2/src/app.module.ts
- api_v2/src/graphql/graphql.ts
- api_v2/src/graphql/schema.gql
- api_v2/src/leaves/leaves.module.ts
- api_v2/src/leaves/leaves.resolver.spec.ts
- api_v2/src/leaves/leaves.resolver.ts
- api_v2/src/leaves/leaves.service.spec.ts
- api_v2/src/leaves/leaves.service.ts
https://framgiaph.backlog.com/view/HRIS-400
- The avatar is null because the function for the file upload hasn't been implemented yet
Commands to run:
-[x] npm run dev
It should show the query for all the leaves of all employees
NestJS Query for all employees leaves
Dotnet Query for all employees leaves
> HRIS-400 [BE] Leave Management: List of Leave > Index
